### ISSUE TITLE
Readme for this tool not clear on unique profile tests

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Interop-Validator#1]
The Readme is obviously originated from copy of the Redfish-Service-Validator.  While there are a few edits to replace the name the differences in operation from that tool are not made clear.  

Does this tool process the special profile schema semantics? How is this accomplished in detail? Are there new errors possible?

It seems the tool ignores the schema reference by the service under test. Is this wise?  

Is the intention to determine of the system under test meets the minimum requirements of the profile?

Suggest the Readme needs more work to make operation clearer. Or point the where this information is available.

**Comment by tomasg2012** [comment]
Seems I forgot to complete the documentation on the README before it was adapted to a public repository, it does execute similarly but with different validation code based on the profile given.

The system being tested should meet the requirements specified by the profile, and any sort of failure is recorded.  I'm not sure what is meant by the first two lines of questions, however.

**Comment by jbobzin-insyde** [comment]
Redfish Recently published DSP-IS0003_0.91a.
Does this tool have anything to do with the contents of that zip?
If no, where does the raw material come from?
Am I mixing up two related efforts?

**Comment by mraineri** [comment]
Basically, the JSON file you see in DSP-IS0003 is what governs how this tool operates. It will crawl the service's resources (in the same manner that the service validator tool does) and check that each of the resources conforms to the requirements specified in the JSON file for the profile. The expectation is that the population of profiles will grow over time, so one of the inputs to the tools will be the JSON file for the profile to test against.

**Comment by jbobzin-insyde** [comment]
Yes, that is reasonable. My issue is the Readme does not currently explain how to set up the test.

**Comment by mraineri** [comment]
I agree; we should fix that! :)

**Comment by mraineri** [comment]
Need to add language like:

The interop validator takes the JSON profile provided by the user and reads each URI on the service. It then performs these checks on each URI:
- Validate all mandatory properties are present
- Validate all properties marked are writable can be written
- Etc

**Comment by mraineri** [comment]
Having lists of errors and what they mean, and what's the likely source of the error in the readme file would be very useful.

**Comment by mraineri** [comment]
Agreed to close 9/14
