### ISSUE TITLE
Exception on handling Links[]

### ISSUE THREAD

**Issue by samerhaj** [DMTF/Redfish-Interop-Validator#10]
When the tool encounters a Links property that is incorrectly implemented as an array (Links[]) rather than a list (Links { } ), it stops running instead of reporting the issue and continuing to run the remaining tests

**Comment by tomasg2012** [comment]
This program utilizes the same traversal code as the Service Validator, such that this error fix can be copied over from the other program.

**Comment by samerhaj** [comment]
Can probably merge the same fix from https://github.com/DMTF/Redfish-Service-Validator/commit/b6f30b914a5537e11e260d4e613b29c4bc422fab
