### ISSUE TITLE
Allow specifying multiple profiles per run

### ISSUE THREAD

**Issue by tomasg2012** [DMTF/Redfish-Interop-Validator#108]
The tool only lets you run multiple profiles if it is required by the parent profile.  Allow the program to specify multiple profiles in one run.

Additionally, consider allowing the program to run multiple profiles concurrently per run instead of running each independently.  This can be arranged by passing in all profiles to the main loop and iterate through them for related keys.

**Comment by tomasg2012** [comment]
Latest pull request rectifies this, but requires more finetuning:

- If possible, create multiple test results for a test_framework payload

- Do not run duplicate profiles, if possible.

**Comment by mraineri** [comment]
Closing; capability not needed at the moment. If someone asks for this, we can add it in the future.
