### ISSUE TITLE
Interop Validator issues from last plugfest (Oct 2020)

### ISSUE THREAD

**Issue by tomasg2012** [DMTF/Redfish-Interop-Validator#110]
brief draft of issues:

- ~If a service changes during runtime, may cause a dictionary failure when combining results of multiple profiles~

- ~LogEntries not limited to 20~

- Validating a profile with --schema exits with incorrect return.

- Repeat messages spam and can flood html/text report, consider capturing repeat messages and report the amount.

**Comment by mraineri** [comment]
Closing; old issue that likely doesn't apply anymore with latest changes. Can file new issues if we need to make further changes in these areas based on the latest version of the tool.
