### ISSUE TITLE
python3 RedfishInteropValidator.py profileName -c config/config.ini -v command is giving error AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by nimmalagautam** [DMTF/Redfish-Interop-Validator#111]
Followed the process in the link " https://github.com/DMTF/Redfish-Interop-Validator " for setting up the Redfish-Interop-Validator and tried to validate the profiles using the command "python3 RedfishInteropValidator.py profileName -c config/config.ini -v" and getting an error **AttributeError: 'NoneType' object has no attribute 'find_all'**

NOTE: ProfileName versioning, for example, HardwareManagement.v1_0_0.json
code downloaded:
https://github.com/DMTF/Redfish-Interop-Validator.git
Branch: Master

 pip list
Package                   Version
------------------------- ---------
beautifulsoup4            4.5.3
bs4                       0.0.1
jsonschema                3.2.0
lxml                      4.6.1
pip                       20.2.4
urllib3                   1.25.10

Command Execute:  python3 RedfishInteropValidator.py HardwareManagement.v1_0_0.json  -c config/config.ini -v
Error: 
Constructing metadata...
getting Schema of $metadata /redfish/v1/$metadata
Should be XML
dont chkauth
callingResourceURI with authtype Session and ssl True: /redfish/v1/$metadata {'OData-Version': '4.0'}
200, [200], {'Allow': 'GET', 'Cache-Control': 'no-cache', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Content-Type': 'application/xml; charset=utf-8', 'Odata-Version': '4.0', 'Vary': 'Accept-Encoding', 'X-Frame-Options': 'sameorigin', 'Date': 'Wed, 04 Nov 2020 12:18:25 GMT', 'Transfer-Encoding': 'chunked'},
TIME ELAPSED: 0.024155
Exception caught while creating Service
Traceback (most recent call last):
  File "RedfishInteropValidator.py", line 435, in main
    currentService = rst.startService(config, default_list)
  File "/home/odimra/Redfish-Interop-Validator/traverseService.py", line 124, in startService
    currentService = rfService(config, defaulted)
  File "/home/odimra/Redfish-Interop-Validator/traverseService.py", line 287, in __init__
    self.metadata = md.Metadata(traverseLogger)
  File "/home/odimra/Redfish-Interop-Validator/metadata.py", line 126, in __init__
    self.schema_obj = rst.rfSchema.getSchemaObject(Metadata.schema_type, Metadata.metadata_uri)
  File "/home/odimra/Redfish-Interop-Validator/rfSchema.py", line 379, in getSchemaObject
    return rfSchema(soup, uri, origin, metadata=metadata, name=typename) if success else None
  File "/home/odimra/Redfish-Interop-Validator/rfSchema.py", line 255, in __init__
    self.refs = getReferenceDetails(soup, metadata, name)
  File "/home/odimra/Redfish-Interop-Validator/rfSchema.py", line 229, in getReferenceDetails
    reftags = maintag.find_all('edmx:Reference', recursive=False)
AttributeError: 'NoneType' object has no attribute 'find_all'
Service could not be started: 'NoneType' object has no attribute 'find_all'

Request to help us to overcome this issue with RedfishInteropValidator

**Comment by billdodd** [comment]
The error seems to be due to an issue retrieving the root element from `/redfish/v1/$metadata`. Can you post the first 10 lines of the payload from the `/redfish/v1/$metadata` URL from the service you are testing?

**Comment by nimmalagautam** [comment]
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ServiceRoot_v1.xml">
        <edmx:Include Namespace="ServiceRoot"/>
        <edmx:Include Namespace="ServiceRoot.v1_5_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/AccountService_v1.xml">
        <edmx:Include Namespace="AccountService"/>
        <edmx:Include Namespace="AccountService.v1_6_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ManagerAccountCollection_v1.xml">
        <edmx:Include Namespace="ManagerAccountCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ManagerAccount_v1.xml">
        <edmx:Include Namespace="ManagerAccount"/>
        <edmx:Include Namespace="ManagerAccount.v1_4_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/SessionService_v1.xml">
        <edmx:Include Namespace="SessionService"/>
        <edmx:Include Namespace="SessionService.v1_1_6"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Session_v1.xml">
        <edmx:Include Namespace="Session"/>
        <edmx:Include Namespace="Session.v1_2_1"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/SessionCollection_v1.xml">
        <edmx:Include Namespace="SessionCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/RoleCollection_v1.xml">
        <edmx:Include Namespace="RoleCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Role_v1.xml">
        <edmx:Include Namespace="Role"/>
        <edmx:Include Namespace="Role.v1_2_4"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ComputerSystemCollection_v1.xml">
        <edmx:Include Namespace="ComputerSystemCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ComputerSystem_v1.xml">
        <edmx:Include Namespace="ComputerSystem"/>
        <edmx:Include Namespace="ComputerSystem.v1_4_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ChassisCollection_v1.xml">
        <edmx:Include Namespace="ChassisCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Chassis_v1.xml">
        <edmx:Include Namespace="Chassis"/>
        <edmx:Include Namespace="Chassis.v1_6_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Resource_v1.xml">
        <edmx:Include Namespace="Resource"/>
        <edmx:Include Namespace="Resource.v1_8_3"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ManagerCollection_v1.xml">
        <edmx:Include Namespace="ManagerCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Manager_v1.xml">
        <edmx:Include Namespace="Manager"/>
        <edmx:Include Namespace="Manager.v1_3_3"/>
        <edmx:Include Namespace="Manager.v1_5_1"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ManagerNetworkProtocol_v1.xml">
        <edmx:Include Namespace="ManagerNetworkProtocol"/>
        <edmx:Include Namespace="ManagerNetworkProtocol.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EventService_v1.xml">
        <edmx:Include Namespace="EventService"/>
        <edmx:Include Namespace="EventService.v1_5_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EventDestinationCollection_v1.xml">
        <edmx:Include Namespace="EventDestinationCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EventDestination_v1.xml">
        <edmx:Include Namespace="EventDestination"/>
        <edmx:Include Namespace="EventDestination.v1_7_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/TaskService_v1.xml">
        <edmx:Include Namespace="TaskService"/>
        <edmx:Include Namespace="TaskService.v1_1_4"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/TaskCollection_v1.xml">
        <edmx:Include Namespace="TaskCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/BootOptionCollection_v1.xml">
        <edmx:Include Namespace="BootOptionCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/BootOption_v1.xml">
        <edmx:Include Namespace="BootOption"/>
        <edmx:Include Namespace="BootOption.v1_0_1"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Task_v1.xml">
        <edmx:Include Namespace="Task"/>
        <edmx:Include Namespace="Task.v1_4_2a"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/MessageRegistryFileCollection_v1.xml">
        <edmx:Include Namespace="MessageRegistryFileCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/MessageRegistryFile_v1.xml">
        <edmx:Include Namespace="MessageRegistryFile"/>
        <edmx:Include Namespace="MessageRegistryFile.v1_1_3"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/MessageRegistry_v1.xml">
        <edmx:Include Namespace="MessageRegistry"/>
        <edmx:Include Namespace="MessageRegistry.v1_0_0"/>
        <edmx:Include Namespace="MessageRegistry.v1_2_0"/>
        <edmx:Include Namespace="MessageRegistry.v1_3_0"/>
        <edmx:Include Namespace="MessageRegistry.v1_3_1"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/MemoryDomainCollection_v1.xml">
        <edmx:Include Namespace="MemoryDomainCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/MemoryCollection_v1.xml">
        <edmx:Include Namespace="MemoryCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Memory_v1.xml">
        <edmx:Include Namespace="Memory"/>
        <edmx:Include Namespace="Memory.v1_7_0"/>
        <edmx:Include Namespace="Memory.v1_7_1"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ProcessorCollection_v1.xml">
        <edmx:Include Namespace="ProcessorCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Processor_v1.xml">
        <edmx:Include Namespace="Processor"/>
        <edmx:Include Namespace="Processor.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Power_v1.xml">
        <edmx:Include Namespace="Power"/>
        <edmx:Include Namespace="Power.v1_3_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/HostInterfaceCollection_v1.xml">
        <edmx:Include Namespace="HostInterfaceCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/HostInterface_v1.xml">
        <edmx:Include Namespace="HostInterface"/>
        <edmx:Include Namespace="HostInterface.v1_1_1"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EthernetInterfaceCollection_v1.xml">
        <edmx:Include Namespace="EthernetInterfaceCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EthernetInterface_v1.xml">
        <edmx:Include Namespace="EthernetInterface"/>
        <edmx:Include Namespace="EthernetInterface.v1_4_1"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/VirtualMediaCollection_v1.xml">
        <edmx:Include Namespace="VirtualMediaCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/VirtualMedia_v1.xml">
        <edmx:Include Namespace="VirtualMedia"/>
        <edmx:Include Namespace="VirtualMedia.v1_2_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/NetworkAdapterCollection_v1.xml">
        <edmx:Include Namespace="NetworkAdapterCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/StorageCollection_v1.xml">
        <edmx:Include Namespace="StorageCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Storage_v1.xml">
        <edmx:Include Namespace="Storage"/>
        <edmx:Include Namespace="Storage.v1_7_1"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Drive_v1.xml">
        <edmx:Include Namespace="Drive"/>
        <edmx:Include Namespace="Drive.v1_8_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Bios_v1.xml">
        <edmx:Include Namespace="Bios"/>
        <edmx:Include Namespace="Bios.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Thermal_v1.xml">
        <edmx:Include Namespace="Thermal"/>
        <edmx:Include Namespace="Thermal.v1_1_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/SecureBoot_v1.xml">
        <edmx:Include Namespace="SecureBoot"/>
        <edmx:Include Namespace="SecureBoot.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/AttributeRegistry_v1.xml">
        <edmx:Include Namespace="AttributeRegistry"/>
        <edmx:Include Namespace="AttributeRegistry.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/PrivilegeRegistry_v1.xml">
        <edmx:Include Namespace="PrivilegeRegistry"/>
        <edmx:Include Namespace="PrivilegeRegistry.v1_0_0"/>
        <edmx:Include Namespace="PrivilegeRegistry.v1_1_4"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Settings_v1.xml">
        <edmx:Include Namespace="Settings"/>
        <edmx:Include Namespace="Settings.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/RedfishExtensions_v1.xml">
        <edmx:Include Namespace="RedfishExtensions.v1_0_0" Alias="Redfish"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/LogEntryCollection_v1.xml">
        <edmx:Include Namespace="LogEntryCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/LogServiceCollection_v1.xml">
        <edmx:Include Namespace="LogServiceCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/NetworkInterfaceCollection_v1.xml">
        <edmx:Include Namespace="NetworkInterfaceCollection"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/LogEntry_v1.xml">
        <edmx:Include Namespace="LogEntry"/>
        <edmx:Include Namespace="LogEntry.v1_1_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/LogService_v1.xml">
        <edmx:Include Namespace="LogService"/>
        <edmx:Include Namespace="LogService.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/FabricCollection_v1.xml">
        <edmx:Include Namespace="FabricCollection"/>
    </edmx:Reference>
</edmx:Edmx>

**Comment by billdodd** [comment]
Thanks for posting the metadata XML. That file looks fine.

Looking more closely, I see that your beautifulsoup4 is at version 4.5.3. This tool requires version 4.6.0 or later. Can you upgrade your beautifulsoup4 and try it again?

**Comment by nimmalagautam** [comment]
But this link https://github.com/DMTF/Redfish-Interop-Validator is asking to use beautifulsoup <=4.5.3

Pre-requisites
beautifulsoup4 - https://pypi.python.org/pypi/beautifulsoup4/4.5.3 (must be <= 4.5.3)

Can we upgrade the version?

**Comment by nimmalagautam** [comment]
Thanks alot for the suggestion, I have upgraded the beautifulsoup4 to  4.9.3 and we are able to go further.

But the https://github.com/DMTF/Redfish-Interop-Validator is asking us to use only <=4.5.3 . Please let us know if it is OK to use the latest version.

**Comment by billdodd** [comment]
Yes, that 4.5.3 reference in the README is out of date. See the requirement in https://github.com/DMTF/Redfish-Interop-Validator/blob/master/requirements.txt

You can (and need to) use 4.6.0 or later. So, yes, the latest version is OK to use.

**Comment by nimmalagautam** [comment]
Thanks a lot for the help and suggestions, with beautifulsoup4 4.9.3 version we were able to go further.

Yes, the requirements.txt is mentioning 4.6.0 version. 
Can we please change the README also mentioning to have beautifulsoup4 version as 4.6.0 or above?

**Comment by billdodd** [comment]
> Thanks a lot for the help and suggestions, with beautifulsoup4 4.9.3 version we were able to go further.
> 
> Yes, the requirements.txt is mentioning 4.6.0 version.
> Can we please change the README also mentioning to have beautifulsoup4 version as 4.6.0 or above?

Yes, I created PR #112 to update the README last night. Thanks for bringing up the issue.
