### ISSUE TITLE
When changing the "ReadRequirement": "Mandatory" to "ReadRequirement": "Recommended" in our profile json file, still the output is giving the ReadRequirement as Mandatory and it is failing

### ISSUE THREAD

**Issue by nimmalagautam** [DMTF/Redfish-Interop-Validator#115]
Command Execute:
python3 RedfishInteropValidator.py ODIMServerHardwareManagement.v1_0_0.json  -c config/config.ini -v

Below are the changes that were done to the parameters of our profile json file and its output when executed are  below 

"EthernetInterface": {
      "MinVersion": "1.6.1",
      **"ReadRequirement": "Recommended"**,
      "PropertyRequirements": {
        "MACAddress": {},
        "SpeedMbps": {},
        "InterfaceEnabled": {},
        "LinkStatus": {},
        "Status": {
          "PropertyRequirements": {
            "Health": {},
            "State": {}
          }
        },
        "HostName": {},
        "FQDN": {},
        "NameServers": {},
        "IPv4Addresses": {
          "PropertyRequirements": {
            "Address": {},
            "SubnetMask": {},
            "AddressOrigin": {},
            "Gateway": {}
          }
        }
      }

OUTPUT:  where it is still showing as Mandatory and failing even after changing the ReadRequirement to Recommended.

EthernetInterface.v1_5_1.EthernetInterface	FQDN.ReadRequirement	    Mandatory	Must Exist	DNE	FAIL
EthernetInterface.v1_5_1.EthernetInterface	SpeedMbps.ReadRequirement	Mandatory	Must Exist	DNE	FAIL
EthernetInterface.v1_5_1.EthernetInterface	HostName.ReadRequirement	Mandatory	Must Exist	DNE	FAIL
EthernetInterface.v1_5_1.EthernetInterface	FQDN.ReadRequirement	    Mandatory	Must Exist	DNE	FAIL
EthernetInterface.v1_5_1.EthernetInterface	Gateway.ReadRequirement	    Mandatory	Must Exist	DNE	FAIL
EthernetInterface.v1_5_1.EthernetInterface	ODIMBaselineHardwareManagement -- SpeedMbps.ReadRequirement	Mandatory	Must Exist	DNE	FAIL
EthernetInterface.v1_5_1.EthernetInterface	ODIMBaselineHardwareManagement -- HostName.Conditional.ReadRequirement	Mandatory	Must Exist	DNE	FAIL
EthernetInterface.v1_5_1.EthernetInterface	ODIMBaselineHardwareManagement -- FQDN.Conditional.ReadRequirement	Mandatory	Must Exist	DNE	FAIL
EthernetInterface.v1_5_1.EthernetInterface	ODIMBaselineHardwareManagement -- Gateway.ReadRequirement	Mandatory	Must Exist	DNE	FAIL

"Power": {
      "PropertyRequirements": {
        "PowerControl": {
          "PropertyRequirements": {
            "PowerConsumedWatts": {
              "ReadRequirement": "Recommended"
            },
            "PowerCapacityWatts": {
              "ReadRequirement": "Recommended"
            },
            "PowerLimit": {
              "ReadRequirement": "Recommended",
              "PropertyRequirements": {
                "LimitInWatts": {},
                "LimitException": {}
OUTPUT of Parameter Power: same for Power, I have changed the Readrequirement to Recommended, but the output is still showing as Mandatory and failing. 

Power.v1_6_0.Power	LimitException.ReadRequirement	Mandatory	Must Exist	DNE	FAIL
Power.v1_6_0.Power	ODIMBaselineHardwareManagement -- LimitException.ReadRequirement	Mandatory	Must Exist	DNE	FAIL
Power.v1_6_0.Power	LimitException.ReadRequirement	Mandatory	Must Exist	DNE	FAIL
Power.v1_6_0.Power	ODIMBaselineHardwareManagement -- LimitException.ReadRequirement	Mandatory	Must Exist	DNE	FAIL

**OUTPUT of Parameter Power: same for Power, I have changed the Readrequirement to Recommended, but the output is still showing as Mandatory and failing. 

Power.v1_6_0.Power	LimitException.ReadRequirement	Mandatory	Must Exist	DNE	FAIL
Power.v1_6_0.Power	ODIMBaselineHardwareManagement -- LimitException.ReadRequirement	Mandatory	Must Exist	DNE	FAIL
Power.v1_6_0.Power	LimitException.ReadRequirement	Mandatory	Must Exist	DNE	FAIL
Power.v1_6_0.Power	ODIMBaselineHardwareManagement -- LimitException.ReadRequirement	Mandatory	Must Exist	DNE	FAIL

**Please let us know how to solve this issue as we need few parameters to be Recommended instead of Mandatory**

**Comment by tomasg2012** [comment]
The ReadRequirement you are changing is not the ReadRequirement of the
properties you are addressing, it is for the resource existing on the
service.  For each of those properties, they MUST exist if the resource
`EthernetInterface` exists in your Service.

In order to get the effect you would want, you would have to apply
`ReadRequirement: "Reccommended"` to each property listed in your profile,
or simply omit those properties.  This applies to all related profiles.

**Comment by mraineri** [comment]
@tomasg2012 is correct; the change you made was to make the "EthernetInterface" resource itself as recommended, but if the resource exists, the properties you have specified are required. For each property you want to mark as recommended, you need to specify that in the property itself. For example:

```
"EthernetInterface": {
    "MinVersion": "1.6.1",
    "PropertyRequirements": {
        "MACAddress": { "ReadRequirement": "Recommended" },
        "SpeedMbps": { "ReadRequirement": "Recommended" },
        "InterfaceEnabled": { "ReadRequirement": "Recommended" },
        "LinkStatus": { "ReadRequirement": "Recommended" },
        "Status": {
            "PropertyRequirements": {
                "Health": { "ReadRequirement": "Recommended" },
                "State": { "ReadRequirement": "Recommended" }
            }
        },
        "HostName": { "ReadRequirement": "Recommended" },
        "FQDN": { "ReadRequirement": "Recommended" },
        "NameServers": { "ReadRequirement": "Recommended" },
        "IPv4Addresses": {
            "PropertyRequirements": {
                "Address": { "ReadRequirement": "Recommended" },
                "SubnetMask": { "ReadRequirement": "Recommended" },
                "AddressOrigin": { "ReadRequirement": "Recommended" },
                "Gateway": { "ReadRequirement": "Recommended" }
            }
        }
    }
}
```

**Comment by mraineri** [comment]
Discussion from the call: The group agrees the tool is behaving as it should; if you're trying to turn required properties to recommended, then use the method shown in the above example.

**Comment by ehsjoar** [comment]
So what we want to accomplish here is that we want the EthernetInterface to be Recommended as part of ComputerSystem. If it is present we want many of the properties that are listed in EthernetInterface to be Mandatory though.  I was thinking the way to do that is to have the EthernetInterface defined as "Recommended" in the ComputerSystem definition and then define EthernetInterface separately with the correct requirements. Should that work?

Thanks,

// Jonas

**Comment by mraineri** [comment]
Yes, that would be a good way of doing that; make "EthernetInterfaces" in "ComputerSystem" recommended, and keep the property requirements in EthernetInterface as-is.
