### ISSUE TITLE
Interop Profiles shouldn't allow for extra entries inside of Resources

### ISSUE THREAD

**Issue by tomasg2012** [DMTF/Redfish-Interop-Validator#117]
Some issues with profiles that have PropertyRequirements or lacking PropertyRequirements, while having those properties incorrectly placed right underneath the Resource tree.

**Comment by mraineri** [comment]
This might actually be an issue with the schema definition of a profile; within the "resource" object, there are a set of properties that are allowed. Looking at the latest published schema definition, "ResourceProfile" does not specify "additionalProperties: false".

**Comment by mraineri** [comment]
Closing; the tool is no longer schema-driven, so this shouldn't be a problem anymore. If we hit this type of issue again, let's file a new issue.
