### ISSUE TITLE
For chassis, even after changing the  "ReadRequirement": "Recommended" for  Contains and ContainedBy , still the result is failing and showing the value as Mandatory

### ISSUE THREAD

**Issue by nimmalagautam** [DMTF/Redfish-Interop-Validator#120]
Changes are done to my profile from mandatory to recommended 

 "Links": {
          "PropertyRequirements": {
            **"Contains": {**
              "ConditionalRequirements": [
                {
                  "Purpose": "Contains is only valid for Racks and RackGroups",
                  "CompareProperty": "ChassiType",
                  "CompareType": "Equal",
                  "CompareValues": [
                    "Rack",
                    "RackGroup"
                  ],
                  **"ReadRequirement": "Recommended",
                  "WriteRequirement": "Recommended"**
                }
              ]
            },
            **"ContainedBy":** {
              "ConditionalRequirements": [
                {
                  "Purpose": "ContainedBy is not valid for RackGroups",
                  "CompareProperty": "ChassiType",
                  "CompareType": "NotEqual",
                  "CompareValues": [ "RackGroup" ],
                  **"ReadRequirement": "Recommended",
                  "WriteRequirement": "Recommended"**
                }
              ]
            },
            "ManagedBy": {
              "ReadRequirement": "Mandatory"
            }

Still, I see the result as a failure in the output as it is showing as Mandatory 

ODIMBaselineHardwareManagement   -- Contains.ReadRequirement | Mandatory
-- | --
ODIMBaselineHardwareManagement --   ContainedBy.ReadRequirement | Mandatory

**Comment by mraineri** [comment]
Is there more to the profile that can be provided? It's not clear to me if "ContainedBy" and "ManagedBy" are properly nested inside of the "Links" requirements.

**Comment by nimmalagautam** [comment]
@mraineri Below is the profile, please let me know if you need more

"Chassis": {
      "MinVersion": "1.13.0",
                        "PropertyRequirements": {
                                "AssetTag": {
                                        "ReadRequirement": "Recommended",
                                        "WriteRequirement": "Recommended"
                                },
                                "ChassisType": {},
                                "IndicatorLED": {
                                        "ReadRequirement": "Recommended",
                                        "WriteRequirement": "Recommended"
                                },
        "Location": {
          "ConditionalRequirements": [
            {
              "Purpose": "Location is mandatory for Racks and RackGroups",
              "CompareProperty": "ChassisType",
              "CompareType": "Equal",
              "CompareValues": [
                "Rack",
                "RackGroup"
              ],
              "ReadRequirement": "Recommended",
              "WriteRequirement": "Recommended"
            }
          ]
        },
                                "Manufacturer": {},
                                "Model": {},
                                "SerialNumber": {},
                                "SKU": {
                                        "ReadRequirement": "Recommended"
                                },
                                "PartNumber": {
                                        "ReadRequirement": "Recommended"
                                },
                                "PowerState": {
                                        "ConditionalRequirements": [
                                                {
                                                        "Purpose": "PowerState is required on Enclosures",
                                                        "CompareProperty": "ChassiType",
                                                        "CompareType": "Equal",
                                                        "CompareValues": [ "Enclosure" ],
                                                        "ReadRequirement": "Mandatory"
                                                }
                                        ]
                                },
                                "Status": {
                                        "PropertyRequirements": {
                                                "State": {},
                                                "Health": {}
                                        }
                                },
                                "Thermal": {
                                        "ReadRequirement": "Recommended"
                                },
                                "Power": {
                                        "ReadRequirement": "Recommended"
                                },
        "Links": {
          "PropertyRequirements": {
            "Contains": {
              "ConditionalRequirements": [
                {
                  "Purpose": "Contains is only valid for Racks and RackGroups",
                  "CompareProperty": "ChassiType",
                  "CompareType": "Equal",
                  "CompareValues": [
                    "Rack",
                    "RackGroup"
                  ],
                  "ReadRequirement": "Recommended",
                  "WriteRequirement": "Recommended"
                }
              ]
            },
            "ContainedBy": {
              "ConditionalRequirements": [
                {
                  "Purpose": "ContainedBy is not valid for RackGroups",
                  "CompareProperty": "ChassiType",
                  "CompareType": "NotEqual",
                  "CompareValues": [ "RackGroup" ],
                  "ReadRequirement": "Recommended",
                  "WriteRequirement": "Recommended"
                }
              ]
            },
            "ManagedBy": {
              "ReadRequirement": "Mandatory"
            }
                                        }
                                },
                                "UUID": {"ReadRequirement": "Recommended"}
                        }
                },

**Comment by mraineri** [comment]
Thanks, that confirms the nesting is correct.

I just noticed a typo in your profile; `CompareProperty` has `ChassiType` and not `ChassisType`. Can you correct that spelling and try running it again?

**Comment by nimmalagautam** [comment]
Still, I see the failure with Mandatory


Contains.ReadRequirement | Mandatory
-- | --
ContainedBy.ReadRequirement | Mandatory


"Chassis": {
      "MinVersion": "1.13.0",
                        "PropertyRequirements": {
                                "AssetTag": {
                                        "ReadRequirement": "Recommended",
                                        "WriteRequirement": "Recommended"
                                },
                                "ChassisType": {},
                                "IndicatorLED": {
                                        "ReadRequirement": "Recommended",
                                        "WriteRequirement": "Recommended"
                                },
        "Location": {
          "ConditionalRequirements": [
            {
              "Purpose": "Location is mandatory for Racks and RackGroups",
              "CompareProperty": "ChassisType",
              "CompareType": "Equal",
              "CompareValues": [
                "Rack",
                "RackGroup"
              ],
              "ReadRequirement": "Recommended",
              "WriteRequirement": "Recommended"
            }
          ]
        },
                                "Manufacturer": {},
                                "Model": {},
                                "SerialNumber": {},
                                "SKU": {
                                        "ReadRequirement": "Recommended"
                                },
                                "PartNumber": {
                                        "ReadRequirement": "Recommended"
                                },
                                "PowerState": {
                                        "ConditionalRequirements": [
                                                {
                                                        "Purpose": "PowerState is required on Enclosures",
                                                        "CompareProperty": "ChassiType",
                                                        "CompareType": "Equal",
                                                        "CompareValues": [ "Enclosure" ],
                                                        "ReadRequirement": "Mandatory"
                                                }
                                        ]
                                },
                                "Status": {
                                        "PropertyRequirements": {
                                                "State": {},
                                                "Health": {}
                                        }
                                },
                                "Thermal": {
                                        "ReadRequirement": "Recommended"
                                },
                                "Power": {
                                        "ReadRequirement": "Recommended"
                                },
        "Links": {
          "PropertyRequirements": {
            "Contains": {
              "ConditionalRequirements": [
                {
                  "Purpose": "Contains is only valid for Racks and RackGroups",
                  "CompareProperty": "ChassisType",
                  "CompareType": "Equal",
                  "CompareValues": [
                    "Rack",
                    "RackGroup"
                  ],
                  "ReadRequirement": "Recommended",
                  "WriteRequirement": "Recommended"
                }
              ]
            },
            "ContainedBy": {
              "ConditionalRequirements": [
                {
                  "Purpose": "ContainedBy is not valid for RackGroups",
                  "CompareProperty": "ChassisType",
                  "CompareType": "NotEqual",
                  "CompareValues": [ "RackGroup" ],
                  "ReadRequirement": "Recommended",
                  "WriteRequirement": "Recommended"
                }
              ]
            },
            "ManagedBy": {
              "ReadRequirement": "Mandatory"
            }
                                        }
                                },
                                "UUID": {"ReadRequirement": "Recommended"}
                        }
                },


2. For Managers can we replace  "ManagerForServers" and  "ManagerForChassis" as Recommended in the below


 "Manager": {
      "PropertyRequirements": {
        "ManagerType": {},
        "UUID": {},
        "Status": {},
        "FirmwareVersion": {"ReadRequirement": "Recommended"},
        "NetworkProtocol": {"ReadRequirement": "Recommended"},
        "EthernetInterfaces": {"ReadRequirement": "Recommended"},
        "LogServices": {
          "ReadRequirement": "IfImplemented"
        },
        "Links": {
          "PropertyRequirements": {
            "ManagerForServers": {
              "ReadRequirement": "Mandatory"
            },
            "ManagerForChassis": {
              "ReadRequirement": "Mandatory"
            }
          }
        }
      },

**Comment by mraineri** [comment]
For 1: We'll need to look into that more; I suspect the tool isn't checking upper-level properties and is only doing comparison checks within the same object.

For 2: Do you mean with regards to "ChassisType" within the Chassis resource? Currently no; the profile syntax doesn't allow for comparisons between two resources like that. But if you just mean generally changing it to recommended, yes, you can do that with your profile.

**Comment by nimmalagautam** [comment]
For1:  Please let me know what info I can provide for further investigation.

For 2: Thanks for the suggestion, I will try to change it to Recommended.

**Comment by nimmalagautam** [comment]
@mraineri  Hello Mike, any update on the issue

**Comment by tomasg2012** [comment]
If I recall, ReadRequirement is Mandatory if not specified for a property
by default, I.e. in the root of `Contains` in the profile.  On top of that,
downgrading the requirement to Recommended via conditionals is not
possible, this was based on how the spec describes it, iirc.

Maybe I misread the issue but that's what issue I was having with another
profile.

**Comment by mraineri** [comment]
That's a good point; I missed over that nuance.

@nimmalagautam can you confirm this is what you're trying to express:

```
if ( ChassisType != RackGroup ) {
    ReadRequirement = Recommended
} else {
    ReadRequirement = Mandatory
}
```

**Comment by nimmalagautam** [comment]
@mraineri  I am trying to change like below

"Links": {
"PropertyRequirements": {
"Contains": {
"ConditionalRequirements": [
{
"Purpose": "Contains is only valid for Racks and RackGroups",
"CompareProperty": "ChassiType",
"CompareType": "Equal",
"CompareValues": [
"Rack",
"RackGroup"
],
"ReadRequirement": "Recommended",
"WriteRequirement": "Recommended"
}
]
},

**Comment by mraineri** [comment]
So, based on how you have constructed that part of the profile, this is essentially what it reads as:
```
if ( ChassisType == RackGroup or ChassisType == Rack ) {
    ReadRequirement = Recommended
} else {
    ReadRequirement = Mandatory
}
```

@nimmalagautam is this the general intent? Mandatory unless ChassisType is "Rack" or "RackGroup"? What's the value of "ChassisType" for the instance in question?

**Comment by mraineri** [comment]
Also please confirm you corrected the spelling of "ChassisType" in your profile because your most recent comment still shows "ChassiType" (missing the 's' between the 'i' and 'T').

**Comment by jautor** [comment]
@nimmalagautam  , @tomasg2012  is correct that you can't "loosen" requirements, only tighten them with the ConditionalRequirements.  Assuming your intent is to make `Contains` a Mandatory requirement for all `ChassisType` except Rack and RackGroup, you would start with a ReadRequirement of "Recommended", then add a ConditionalRequirement for "values != Rack or RackGroup" with a ReadRequirement of Mandatory.  That way you build up the requirements from least restrictive to most restrictive.

**Comment by nimmalagautam** [comment]
@mraineri , Yeah I have changed the ChassiType to ChassisType in my profile.

Sorry, My bad that I have copied from the above comment. That's why you are seeing the wrong word

**Comment by mraineri** [comment]
So, based on comments from @jautor and @tomasg2012, you can't actually do what you're specifying. There's a note in the "Conditional requirements" clause in the Redfish Interoperability Profile spec with regards to this:
> Note that a condition cannot override or weaken a requirement already specified.

So, since the root requirement already makes it "Mandatory", you can't use conditions to weaken it to "Recommended". As @jautor suggested, you should start with "Recommended" in the root requirement, and then build on that to upgrade it to Mandatory for other cases.

```
"Links": {
    "PropertyRequirements": {
        "ReadRequirement": "Recommended",
        "Contains": {
            "ConditionalRequirements": [
                {
                    "Purpose": "Contains is required for cases other than Racks and RackGroups",
                    "CompareProperty": "ChassisType",
                    "CompareType": "NotEqual",
                    "CompareValues": [
                        "Rack",
                        "RackGroup"
                    ],
                    "ReadRequirement": "Mandatory"
                }
            ]
        }
    }
}
```

**Comment by ehsjoar** [comment]
Hi Guys,

Thanks for all the comments. I get that "Links" would have to be there if no specific ReadRequirement has been specified as "Recommented". All good with that. But are you saying that because of this, all properties under it will also become mandatory independently of any extra specification (e.g. Recommended for "Contains")?

Thanks,

// Jonas

**Comment by mraineri** [comment]
No, we're not saying that. What we're saying is because "Contains" in your profile starts off as "Mandatory", it's not possible to use a conditional override to loosen "Contains" to be "Recommended".

I also just realized there's a mistake in what I put above. Here's the correction:

```
"Links": {
    "PropertyRequirements": {
        "Contains": {
            "ReadRequirement": "Recommended",
            "ConditionalRequirements": [
                {
                    "Purpose": "Contains is required for cases other than Racks and RackGroups",
                    "CompareProperty": "ChassisType",
                    "CompareType": "NotEqual",
                    "CompareValues": [
                        "Rack",
                        "RackGroup"
                    ],
                    "ReadRequirement": "Mandatory"
                }
            ]
        }
    }
}
```

**Comment by ehsjoar** [comment]
Thanks Mike,

It is clear now finally :-)

Cheers,

// Jonas

**Comment by mraineri** [comment]
@ehsjoar @nimmalagautam can you confirm the recommendation for your profile resolved the issue?

**Comment by nimmalagautam** [comment]
@mraineri  After changing the profile according to your suggestion, still we see Contains for condition for Chassis is failing
"Links": {
          "PropertyRequirements": {
            "Contains": {
              "ReadRequirement": "Recommended",
              "ConditionalRequirements": [
                {
                  "Purpose": "Contains is only valid for Racks and RackGroups",
                  "CompareProperty": "ChassisType",
                  "CompareType": "NotEqual",
                  "CompareValues": [
                    "Rack",
                    "RackGroup"
                  ],
                  "ReadRequirement": "Mandatory",
                  "WriteRequirement": "Mandatory"
                }
              ]
            },
            

1 fail.Contains.Conditional.ReadRequirement errors in /redfish/v1/Chassis/80cc6265-6d80-43ca-9048-e972d6ef66e7:1
1 fail.Contains.Conditional.ReadRequirement errors in /redfish/v1/Chassis/3fce3951-dd5c-4413-8b35-c4ee9fda736c:1
1 fail.Contains.Conditional.ReadRequirement errors in /redfish/v1/Chassis/bedc2b3d-41a6-4f81-8192-9fdfaba9b6bb
1 fail.Contains.Conditional.ReadRequirement errors in /redfish/v1/Chassis/f18202b5-ca45-42c0-9b38-c59fdbf50f80
1 fail.Contains.Conditional.ReadRequirement errors in /redfish/v1/Chassis/c73a31af-77d8-4a51-b7cb-e42ccf2aa46d
1 fail.Contains.Conditional.ReadRequirement errors in /redfish/v1/Chassis/c8aa108c-5d93-491a-b26e-2feccc334402
1 fail.Contains.Conditional.ReadRequirement errors in /redfish/v1/Chassis/9c74a92f-a6a2-4cb6-8962-f75d9ff26fdc

**Comment by mraineri** [comment]
Can you please provide the report?

**Comment by nimmalagautam** [comment]
@mraineri  Please let me know which report you are looking for ?

**Comment by mraineri** [comment]
The test report from your latest run with the profile containing:

```
"Links": {
    "PropertyRequirements": {
        "Contains": {
            "ReadRequirement": "Recommended",
            "ConditionalRequirements": [
                {
                    "Purpose": "Contains is required for cases other than Racks and RackGroups",
                    "CompareProperty": "ChassisType",
                    "CompareType": "NotEqual",
                    "CompareValues": [
                        "Rack",
                        "RackGroup"
                    ],
                    "ReadRequirement": "Mandatory"
                }
            ]
        }
    }
}
```

**Comment by nimmalagautam** [comment]
@mraineri I have executed the latest profile validation with  profile containing 

"Links": {
    "PropertyRequirements": {
        "Contains": {
            "ReadRequirement": "Recommended",
            "ConditionalRequirements": [
                {
                    "Purpose": "Contains is required for cases other than Racks and RackGroups",
                    "CompareProperty": "ChassisType",
                    "CompareType": "NotEqual",
                    "CompareValues": [
                        "Rack",
                        "RackGroup"
                    ],
                    "ReadRequirement": "Mandatory"
                }
            ]
        }
    }
}
and the report is below
[InteropHtmlLog05_18_2021_061128_latest.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/6505692/InteropHtmlLog05_18_2021_061128_latest.zip)

**Comment by tomasg2012** [comment]
I'm assuming in terms of this conditional, ChassisType is either Rack or RackGroup?  Since the report doesn't show the payloads for the Interop Validator, I can't know for sure.

**Comment by mraineri** [comment]
You're right, I thought it would have a payload button to show what was in the resource.

Can the response payload for one of the failing resources be provided (such as `/redfish/v1/Chassis/b38872ae-0d6c-43c2-b4bd-f65b3d468123:1`)?

**Comment by nimmalagautam** [comment]
@mraineri  Please let us know about this Link issue. I mean what changes we need to do to overcome this.

"Links": {
"PropertyRequirements": {
"Contains": {
"ReadRequirement": "Recommended",
"ConditionalRequirements": [
{
"Purpose": "Contains is required for cases other than Racks and RackGroups",
"CompareProperty": "ChassisType",
"CompareType": "NotEqual",
"CompareValues": [
"Rack",
"RackGroup"
],
"ReadRequirement": "Mandatory"
}
]
}
}
}

**Comment by mraineri** [comment]
@nimmalagautam I'd like to review one of the failing resources is possible. Could you please provide a copy of `/redfish/v1/Chassis/b38872ae-0d6c-43c2-b4bd-f65b3d468123:1` or one of the other failing Chassis resources?

**Comment by nimmalagautam** [comment]
@mraineri 
Please find the copy of /redfish/v1/Chassis/b38872ae-0d6c-43c2-b4bd-f65b3d468123:1

[chassis.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/6652570/chassis.zip)

**Comment by mraineri** [comment]
So, the error looks correct to me. The ChassisType property is `RackMount`, which is not equal to `Rack` or `RackGroup`, making the property mandatory.

If you don't want Contains as a required property for `RackMount`, then that needs to be added to the list in `CompareValues`.

**Comment by nimmalagautam** [comment]
@mraineri 
Hi Mike,

I have updated the profile with RackMount in CompareValues 

"Links": {
          "PropertyRequirements": {
            "Contains": {
              "ReadRequirement": "Recommended",
              "ConditionalRequirements": [
                {
                  "Purpose": "Contains is only valid for Racks and RackGroups",
                  "CompareProperty": "ChassisType",
                  "CompareType": "NotEqual",
                  "CompareValues": [
                    "Rack",
                    "RackGroup",
                    "RackMount"
                  ],
                  "ReadRequirement": "Mandatory",
                  "WriteRequirement": "Mandatory"
                }
              ]
            },

Still, the Contains for Chassis is failing 

1 fail.ContainedBy.ReadRequirement errors in /redfish/v1/Chassis/9a388fec-89b2-4fa8-a83f-19734aff97f9:1
**1 fail.Contains.Conditional.ReadRequirement errors in /redfish/v1/Chassis/9a388fec-89b2-4fa8-a83f-19734aff97f9:1**
1 fail.Location.ReadRequirement errors in /redfish/v1/Chassis/9a388fec-89b2-4fa8-a83f-19734aff97f9:1
1 fail.ContainedBy.ReadRequirement errors in /redfish/v1/Chassis/fc54367f-d810-4246-9b6b-a19b29379268:1
**1 fail.Contains.Conditional.ReadRequirement errors in /redfish/v1/Chassis/fc54367f-d810-4246-9b6b-a19b29379268:1**
1 fail.Location.ReadRequirement errors in /redfish/v1/Chassis/fc54367f-d810-4246-9b6b-a19b29379268:1

Attaching the ZIP file which contains the test report of the profile validation, copy of **/redfish/v1/Chassis/9a388fec-89b2-4fa8-a83f-19734aff97f9:1** and **/redfish/v1/Chassis/fc54367f-d810-4246-9b6b-a19b29379268:1**

[logs_chassis_after_change_RackMount.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/6662647/logs_chassis_after_change_RackMount.zip)


Please let me know if I am missing anything

**Comment by mraineri** [comment]
I should be able to do some local testing with this info; I'll let you know what I find.

**Comment by mraineri** [comment]
I've been able to test out your samples and was able to reproduce the issue. Please test out branch "Fix120-Comparison-Fixes" to confirm on your side.

**Comment by nimmalagautam** [comment]
@mraineri Please let me know if the below-mentioned profiles are OK with your new branch

"**Location**": {
          "ConditionalRequirements": [
            {
              "Purpose": "Location is mandatory for Racks and RackGroups",
              "CompareProperty": "ChassisType",
              "CompareType": "Equal",
              "CompareValues": [
                "Rack",
                "**RackMount**",
                "RackGroup"
              ],
              "ReadRequirement": "Recommended",
              "WriteRequirement": "Recommended"
            }
          ]
        },

"Links": {
          "PropertyRequirements": {
            "**Contains**": {
              "ReadRequirement": "Recommended",
              "ConditionalRequirements": [
                {
                  "Purpose": "Contains is only valid for Racks and RackGroups",
                  "CompareProperty": "ChassisType",
                  "CompareType": "NotEqual",
                  "CompareValues": [
                    "Rack",
                    "RackGroup",
                    "**RackMount**"
                  ],
                  "ReadRequirement": "Mandatory",
                  "WriteRequirement": "Mandatory"
                }
              ]
            },

**ContainedBy**": {
              "ConditionalRequirements": [
                {
                  "Purpose": "ContainedBy is not valid for RackGroups",
                  "CompareProperty": "ChassisType",
                  "CompareType": "NotEqual",
                  "CompareValues": [ "RackGroup", "**RackMount**" ],
                  "ReadRequirement": "Recommended",
                  "WriteRequirement": "Recommended"
                }
              ]
            },

**Comment by mraineri** [comment]
You'll need to adjust the rules for Location and ContainedBy; those will exhibit the first problem we saw where you start with a strict rule and try to weaken it. Both ContainedBy and Location start off as mandatory, and then you're trying to weaken them when they're not Rack/RackGroup/RackMount.

I would revisit those definitions first to match the pattern being used for Contains to start off with a weaker requirement, and then strengthen it with the condition.

**Comment by nimmalagautam** [comment]
@mraineri With the new Branch, I don't see any failures for Contains nor ContainedBy for the Rack/RackGroup/RackMount.

I remember you asking me to update the profile with RackMount in CompareValues and  "CompareType": "NotEqual".

Please let me know if I can have RackMount in CompareValues and "CompareType": "NotEqual"

**Comment by mraineri** [comment]
If you're intent is the following logic:
```
if( ChassisType != "RackMount" and ChassisType != "Rack" and ChassisType != "RackGroup" ) {
    ReadRequirement = "Mandatory"
} else {
    ReadRequirement = "Recommended"
}
```

Then yes, include RackMount. Ultimately I do not know what it is you're really trying to specify and I'm inferring this based on the error message and payload provided.

**Comment by nimmalagautam** [comment]
@mraineri  Thanks for the suggestion, will check it in this way.



And with the new Branch, I am unable to execute the profile validation for the 2nd time with few changes to the profile. It is giving me the same result without running it.

command executed:  python3 RedfishInteropValidator.py ODIMServerHardwareManagement.v1_0_0.json  -c config.ini -v

I have tried to do few changes to the ODIMServerHardwareManagement.v1_0_0.json and then tried to run the validator, it is coming out with the same result within no time. We dint see this behaviour with the old validator
**Elapsed time: 0:00:00**

**Comment by mraineri** [comment]
Can you please provide the full console output?

**Comment by nimmalagautam** [comment]
Hi @mraineri  Below are the changes that I was trying to do

"Links": {
          "PropertyRequirements": {
            "Contains": {
              "ConditionalRequirements": [
                {
                  "Purpose": "Contains is only valid for Racks and RackGroups",
                  "CompareProperty": "ChassisType",
                  "CompareType": "NotEqual",
                  "CompareValues": [
                    "Rack",
                    "RackGroup"
                  ],
                  "ReadRequirement": "Mandatory",
                  "WriteRequirement": "Mandatory"
                }
              ]
            },
            "ContainedBy": {
              "ConditionalRequirements": [
                {
                  "Purpose": "ContainedBy is not valid for RackGroups",
                  "CompareProperty": "ChassisType",
                  "CompareType": "NotEqual",
                  "CompareValues": [ "RackGroup" ],
                  "ReadRequirement": "Mandatory",
                  "WriteRequirement": "Mandatory"
                }
              ]
            },

full console output of the command:  python3 RedfishInteropValidator.py ODIMServerHardwareManagement.v1_0_0.json -c config.ini -v 
[InteropLog_06_18_2021_054229.txt](https://github.com/DMTF/Redfish-Interop-Validator/files/6676986/InteropLog_06_18_2021_054229.txt)

**Comment by mraineri** [comment]
Can you check your connectivity to the DMTF site? The tool isn't even testing the service since it's not pulling down the schema files.

**Comment by nimmalagautam** [comment]
@mraineri  We do not have Internet active in the machine where we run the profile validator as it will create connection issues to our ODIM.  Without the Internet also the validator used to run and provide results. But with the new validator, it is not the case.
Unable to run for the second time after changes done to our profiles.

**Comment by nimmalagautam** [comment]
@mraineri seems like the new Branch Fix120-Comparison-Fixes doesn't have the metadata under Schemafiles. So copied them from the old branch.  ANd the validator is working fine now.

Thanks a lot for your support. Will get back to you if facing any issues.

**Comment by mraineri** [comment]
The branch is a fresh copy; that directly is built automatically by the tool when it's not present (it will go pull the files from the service or the DMTF site). So, a clean checkout of the tool will not have that directory automatically. I suspect you successfully pulled the metadata once with the tool.

**Comment by nimmalagautam** [comment]
@mraineri  Yes the git pull of the new branch did not provide me the Schema Directory, so I was using my old Schema directory. 
Please let me know how to get the Schema directory after the git pull of the branch is done. As my old Schema directory is not helping me to solve my issue. With the old Schema directory still, I am facing the same old issue with ContainedBy failing

**Comment by nimmalagautam** [comment]
Hi @mraineri , below is the profile used with the new Branch 

"Links": {
          "PropertyRequirements": {
            "Contains": {
              "ReadRequirement": "Recommended",
              "ConditionalRequirements": [
                {
                  "Purpose": "Contains is only valid for Racks and RackGroups",
                  "CompareProperty": "ChassisType",
                  "CompareType": "NotEqual",
                  "CompareValues": [
                    "Rack",
                    "RackGroup",
                    "RackMount"
                  ],
                  "ReadRequirement": "Mandatory",
                  "WriteRequirement": "Mandatory"
                }
              ]
            },
            "ContainedBy": {
              "ConditionalRequirements": [
                {
                  "Purpose": "ContainedBy is not valid for RackGroups",
                  "CompareProperty": "ChassisType",
                  "CompareType": "NotEqual",
                  "CompareValues": [ "RackGroup", "RackMount" ],
                  "ReadRequirement": "Mandatory",
                  "WriteRequirement": "Mandatory"
                }
              ]
            },

Still getting the failures 

1 fail.EventFormatType.PropertyValidity errors in /redfish/v1/EventService
1 fail.ContainedBy.ReadRequirement errors in /redfish/v1/Chassis/9a388fec-89b2-4fa8-a83f-19734aff97f9:1
1 fail.Contains.Conditional.ReadRequirement errors in /redfish/v1/Chassis/9a388fec-89b2-4fa8-a83f-19734aff97f9:1
1 fail.Location.ReadRequirement errors in /redfish/v1/Chassis/9a388fec-89b2-4fa8-a83f-19734aff97f9:1
