### ISSUE TITLE
For chassis, even after changing the "ReadRequirement": "Recommended" for Location and ContainedBy , still the result is failing and showing the value as Mandatory with the new validator

### ISSUE THREAD

**Issue by nimmalagautam** [DMTF/Redfish-Interop-Validator#123]
Hi @mraineri 
I have successfully pulled the metadata into the machine where I am running the validator.

Still, I am facing the error for the below profiles with the Branch which you suggested

PROFILES:

"**Location**": {
          "ConditionalRequirements": [
            {
              "Purpose": "Location is mandatory for Racks and RackGroups",
              "CompareProperty": "ChassisType",
              "CompareType": "NotEqual",
              "CompareValues": [
                "Rack",
                "RackMount",
                "RackGroup"
              ],
              "ReadRequirement": "Recommended",
              "WriteRequirement": "Recommended"
            }
          ]
        },

"Links": {
          "PropertyRequirements": {
            "Contains": {
              "ReadRequirement": "Recommended",
              "ConditionalRequirements": [
                {
                  "Purpose": "Contains is only valid for Racks and RackGroups",
                  "CompareProperty": "ChassisType",
                  "CompareType": "NotEqual",
                  "CompareValues": [
                    "Rack",
                    "RackGroup",
                    "RackMount"
                  ],
                  "ReadRequirement": "Recommended",
                  "WriteRequirement": "Recommended"
                }
              ]
            },
            "**ContainedBy**": {
              "ConditionalRequirements": [
                {
                  "Purpose": "ContainedBy is not valid for RackGroups",
                  "CompareProperty": "ChassisType",
                  "CompareType": "NotEqual",
                  "CompareValues": [ "RackGroup","RackMount" ],
                  "ReadRequirement": "Recommended",
                  "WriteRequirement": "Recommended"
                }
              ]
            },

**FAILURES**:
1 fail.**ContainedBy.ReadRequirement** errors in /redfish/v1/Chassis/9a388fec-89b2-4fa8-a83f-19734aff97f9:1
1 fail.**Location.ReadRequirement** errors in /redfish/v1/Chassis/9a388fec-89b2-4fa8-a83f-19734aff97f9:1

[24-06-2021.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/6708364/24-06-2021.zip)

**Comment by mraineri** [comment]
Both your definition for Location and ContainedBy are following the same sorts of issues before; with the way the profile is written, you're starting off by making them required and then weakening them to be recommended, which is not something supported.

"ReadRequirement" needs to be specified in the root of "ContainedBy" and "Location" with something other than mandatory; not specifying it at all defaults the requirement to mandatory.

**Comment by mraineri** [comment]
Essentially:

```
"Location": {
  <Base read requirement needs to be specified here, otherwise it's mandatory>
  "ConditionalRequirements": [
    {
      "Purpose": "Location is mandatory for Racks and RackGroups",
      "CompareProperty": "ChassisType",
      "CompareType": "NotEqual",
      "CompareValues": ["Rack","RackMount","RackGroup"],
      "ReadRequirement": "Recommended",  <-- This condition will not weaken the base requirement
      "WriteRequirement": "Recommended"
    }
  ]
},
"Links": {
  "PropertyRequirements": {
    "Contains": {
      "ReadRequirement": "Recommended",
      "ConditionalRequirements": [
        {
          "Purpose": "Contains is only valid for Racks and RackGroups",
          "CompareProperty": "ChassisType",
          "CompareType": "NotEqual",
          "CompareValues": ["Rack","RackGroup","RackMount"],
          "ReadRequirement": "Recommended",  <-- Since you're starting as recommended, this condition doesn't do anything
          "WriteRequirement": "Recommended"
        }
      ]
    },
    "ContainedBy": {
      <Base read requirement needs to be specified here, otherwise it's mandatory>
      "ConditionalRequirements": [
        {
          "Purpose": "ContainedBy is not valid for RackGroups",
          "CompareProperty": "ChassisType",
          "CompareType": "NotEqual",
          "CompareValues": [ "RackGroup","RackMount" ],
          "ReadRequirement": "Recommended",  <-- This condition will not weaken the base requirement
          "WriteRequirement": "Recommended"
        }
      ]
    },
```

**Comment by nimmalagautam** [comment]
Hi @mraineri 
Thanks for the suggestion, Yes I have already verified long back with your suggestion by placing

**Comment by mraineri** [comment]
It depends on what you're trying to establish for rules in your profile. As long as you start with a weak requirement, and use a condition to strengthen it, that's valid. The original issue raised by others was you were trying to do the opposite (start with a strong requirement and weaken it with a condition).

**Comment by nimmalagautam** [comment]
@mraineri Thanks for the suggestion... 

Can we close the issue.

**Comment by nimmalagautam** [comment]
Hi @mraineri 

We have observed few errors in the profile validation like below.  

ERROR - The following schema URIs referenced from $metadata could not be retrieved:
http://redfish.dmtf.org/schemas/v1/FirmwareInventoryCollection_v1.xml
http://redfish.dmtf.org/schemas/v1/EthernetInterfaces_v1.xml
http://redfish.dmtf.org/schemas/v1/FirmwareInventory_v1.xml


Attaching the profile console output and the HTML
[29062021.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/6730788/29062021.zip)
 file


Please let us know how to overcome these errors as the profile validation is giving the failure output 

Rendering HTML Log
Counter({'passGet': 444, 'pass': 411, 'totaltests': 408, 'warningPresent': 235, 'metadataNamespaces': 172, 'serviceNamespaces': 100, 'failErrorPresent': 40, 'missingNamespaces': 10, 'warn': 8, 'badSchemaUris': 3, 'badNamespaceInclude': 2, 'errorProfileValidityError': 1, 'fail.EventFormatType.PropertyValidity': 1, 'fail.Links.ReadRequirement': 1})
**Validation has failed: 47 problems found**

**Comment by mraineri** [comment]
You need to correct your service's schema references. The files "FirmwareInventoryCollection_v1.xml", "EthernetInterfaces_v1.xml", and "FirmwareInventory_v1.xml" do not exist in the standard.

"FirmwareInventory" in the UpdateService is defined in the "SoftwareInventory_v1.xml" schema; both "FirmwareInventory" and "SoftwareInventory" share the same schema definitions (but the context they support is different).

"EthernetInterfaces_v1.xml" is either going to be "EthernetInterface_v1.xml" or "EthernetInterfaceCollection_v1.xml" (depending on what the resource you're trying to model is).
