### ISSUE TITLE
validateMinVersion performs string comparison rather than integer comparison

### ISSUE THREAD

**Issue by Eccomiqua** [DMTF/Redfish-Interop-Validator#126]
Usage of MinVersion in Interop profiles does not evaluate correctly because it is performing string comparison rather than int comparison.  For instance, for a service with a resource having version 1.15.0 for a given resource, the validator will fail for a profile specifying a min version of 1.5.2 for that resource.  It ends up checking '15' > '5' and returns False in validateMinVersion.  Converting to int before the comparison will resolve the issue.

**Comment by tomasg2012** [comment]
This checks out.  This logic was changed in Service-Validator a while ago but not here.

**Comment by mraineri** [comment]
PR with the fix has been merged
