### ISSUE TITLE
'Int' Type value in value of property key-value pair is colliding with get() operations

### ISSUE THREAD

**Issue by arahimanshaik** [DMTF/Redfish-Interop-Validator#129]
While Using Interop-Validator against profile with properties which have 'Int' Type value in property Key-value pair, It fails as Interop Validator is trying to perform get operation on 'Int' value.

For Instance,  in Line 297 of [OCPDoorHeatExchangerHardwareManagement profile](https://github.com/opencomputeproject/HWMgmt-OCP-Profiles/blob/master/RackAndPower/OCPDoorHeatExchangerHardwareManagement.v0_0_5.json) the value is 'Int' type and we cannot perform 'Dict' get() operation on it.

Output:
ERROR - Something went wrong
Traceback (most recent call last):
  File "/home/bruce/Redfish-Interop-Validator-master/validateResource.py", line 167, in validateSingleURI
    propMessages, propCounts = interop.validateInteropResource(propResourceObj, objRes, jsondata)
  File "Redfish-Interop-Validator-master/common/interop.py", line 585, in validateInteropResource
    pmsgs, pcounts = validatePropertyRequirement(
  File "Redfish-Interop-Validator-master/common/interop.py", line 375, in validatePropertyRequirement
    comparisonValue = v.get("Comparison", "AnyOf") if v.get("Values") is not None else None
AttributeError: 'int' object has no attribute 'get'
ERROR - Could not finish validation check on this payload

**Comment by tomasg2012** [comment]
MinCount should not be in Property Requirements, but instead a level above it, to my understanding.

**Comment by mraineri** [comment]
@tomasg2012 is correct; essentially with MinCount at the level you're using it, the tool is looking for a "MinCount" property in the response body, and all definitions at that level are expected to be dictionaries containing property requirements.

Did correcting the profile syntax resolve the issue?

**Comment by arahimanshaik** [comment]
@mraineri @tomasg2012 Yes, Its resolved after the positional change in the Profile. Thank you @tomasg2012.
