### ISSUE TITLE
Basic server profile

### ISSUE THREAD

**Issue by billdodd** [DMTF/Redfish-Interop-Validator#14]
Has the Basic Server Profile been publically published? If so, can we include it here in the profiles subdirectory? That will be convenient for building the test tree for the Redfish-Test-Framework.

**Comment by mraineri** [comment]
There is a version of the Basic Server Profile that has been published. It can be found in the IS0003 bundle here: https://www.dmtf.org/sites/default/files/standards/documents/DSP-IS0003_0.91a.zip

**Comment by jautor** [comment]
That has been published ONLY has a work in progress.  I would not include it in any bundle here as it would be mixing "WIP" items with published/approved components.  We don't want anyone to accidentally treat that work as final.

**Comment by mraineri** [comment]
Beyond that, there hasn't been anything published to date. So, if we shouldn't put that in this repo, then we shouldn't be putting anything in.

**Comment by billdodd** [comment]
Got it. Thanks for the input.
