### ISSUE TITLE
Validator fails to close RF session after validation completes

### ISSUE THREAD

**Issue by jyundt** [DMTF/Redfish-Interop-Validator#140]
When using RF sessions via `--authtype Session`, the RF session generated is not deleted after the validation process finishes.

**Comment by mraineri** [comment]
Looks like there's no cleanup to call the `logout` method when done testing; certainly needs to be added...

**Comment by JordanCHW** [comment]
> Best option would update it to the same methodology of the Service-Validator, which uses the official redfish python library to handle connections. The Interop Validator does not, and uses an older manual method.
> 
> Though a similar issue is in the Service-Validator, as "closing" the connection doesn't run the logout command.

+1 
It would be more convenient to have the same methodology with Service-Validator.

**Comment by tomasg2012** [comment]
I would agree, but the current PR seems to be satisfactory.  Doing updates to the codebase can be done in another issue.
