### ISSUE TITLE
Unable to specify list of acceptable values for Property

### ISSUE THREAD

**Issue by jyundt** [DMTF/Redfish-Interop-Validator#145]
Related to [this forum thread](https://redfishforum.com/thread/636/specifying-list-values-property), I'm trying to specify a list of acceptable values for a mandatory property. However, using a test case with intentionally bad values does not result in a failure.

Snippet of what I'm trying to run:
```
{
        "SchemaDefinition": "RedfishInteroperabilityProfile.v1_5_0",
        "ProfileName": "test",
        "ProfileVersion": "0.0.1",
        "Resources": {
                "Chassis": {
                        "PropertyRequirements": {
                                "ChassisType": {
                                        "Comparison": "AnyOf",
                                        "Values": [
                                                "Enclosure",
                                                "RackMount",
                                                "StorageEnclosure"
                                        ]
                                }
                        }
                }
        }
}
```

Test case that should fail (but doesn't seem to be failing):
```
{
        "SchemaDefinition": "RedfishInteroperabilityProfile.v1_5_0",
        "ProfileName": "test",
        "ProfileVersion": "0.0.1",
        "Resources": {
                "Chassis": {
                        "PropertyRequirements": {
                                "ChassisType": {
                                        "Comparison": "AnyOf",
                                        "Values": [ 
                                                "Foo",
                                                "Bar"
                                        ]
                                }
                        }
                }
        }
}
```

Log output:
- [InteropHtmlLog_04_04_2022_164410.html](https://redfishforum.com/attachment/download/53)
- [InteropLog_04_04_2022_164410.txt](https://redfishforum.com/attachment/download/54)

**Comment by tomasg2012** [comment]
The interpretation of the Interop Specification seems to be totally different.  From what I can tell, AnyOf and AllOf apply to a list of properties or multiple resources, while "Equal" should be the case in this Comparison.   It should still be verbose about what's going on, but that's my understanding.

Since I had written this a while ago, is this logic incorrect?

**Comment by mraineri** [comment]
I think you might be correct now that I'm re-reading the spec... Let me ask @jautor

**Comment by tomasg2012** [comment]
In any case, NotEqual is explicit about being multiple values, but Equal only says one value, so this may have been misinterpreted for a while.

**Comment by mraineri** [comment]
We may have over-designed the profile and made two things really identical; talking to @jautor about it now.

**Comment by mraineri** [comment]
It seems a bit more complicated than list vs non-list. AnyOf is supposed to be a check across all properties of that name in the resource, whereas Equal is an exact check for a given property. For this usage, there's only one instance of that property in the resource, so they're really equivalent here.

**Comment by mraineri** [comment]
@tomasg2012 pointed me to other material in the schema definition for the profile:
> The values used to perform a `Comparison`.  Multiple values are only allowed for `AnyOf` or `AllOf` comparisons.  If no `Comparison` property is present, the comparison is assumed to be an `AnyOf` comparison.

Going based off this and the example in the profile spec, the intent is where you have an array of objects, and you need to make sure the property in at least one object instance has one of the referenced values.

So, @jyundt, since in your example profile, `Equal` is the right comparison type to use. Sorry for the churn!

**Comment by mraineri** [comment]
Sorry, I'm reading it a bit differently now. "Multiple values are only allowed for AnyOf or AllOf comparison", meaning the length of the "Values" term?

With that, and this statement in the spec, I don't think we have a really good and simple proper "AnyOf" check for a singleton property.
> At least one instance of the property in this resource must be equal to one of the values listed.

While `Equal` technically isn't supposed to be used with multiple values, you could actually use it that way...

**Comment by tomasg2012** [comment]
It's a bit nebulous, the tool also does seem to mix this up anyway;  I think checkConditionalRequirements with CompareType "AnyOf" does function as the first post expects it to, but specifically, the program does not let checkConditional apply "AnyOf"/"AllOf" to PropertyRequirements _unless_ it's a list.  So these two should match, and don't.

I guess there's a few factors, and the discretion of the user's profile, the payload and the tool itself.  maybe a set of cases needs to be written up...

**Comment by jyundt** [comment]
> So, @jyundt, since in your example profile, Equal is the right comparison type to use. Sorry for the churn!

Ah yes, I think this is working for me so far, thank you for digging into this!

**Comment by mraineri** [comment]
@jyundt after speaking with @jautor we will need to do some work with the tool and spec to make things clearer from the design intent. But, for your particular usage here, are you trying to ensure that all Chassis resources contain a ChassisType with one of the values listed, or at least one Chassis resource in the service contains a ChassisType property with one of the values listed?

If it's the first case (every Chassis resource needs to have a ChassisType property that fits), then Equal should be used.
If it's the second case (at least one Chassis resource contains one of the values listed), then AnyOf should be used.

**Comment by jyundt** [comment]
I'm looking for:

> ensure that all Chassis resources contain a ChassisType with one of the values listed

**Comment by mraineri** [comment]
Thanks for confirming; that would be a case for using Equal.

We'll need to do work on the spec and tool for the AnyOf case, but it sounds like you're all set for what you're trying to do.

**Comment by mjendrysik-hpe** [comment]
I am also running into this problem when trying to make sure a given implementation is reporting GPUs properly.
