### ISSUE TITLE
How to apply different requirements for the resoruces shared the same parent resource

### ISSUE THREAD

**Issue by JordanCHW** [DMTF/Redfish-Interop-Validator#152]
Let's say we want to have different requirements for LogEntry resources located in `/redfish/v1/Systems/{SystemId}/LogServices/{LoggerA}/Entries/{Id}` and `/redfish/v1/Systems/{SystemId}/LogServices/{LoggerB}/Entries/{Id}`, how could we achieve that? 

I tried `URIs` and `SubordinateToResource` but both of them are not suitable. 
For `URIs`, we definitely couldn't specify all log entries. 
For `SubordinateToResource`, in this case, their parents are exactly the same (`["ComputerSystem", "LogService"]`), so we can't apply different requirements to them. 

Is there any other options? If not, is it possible to extend the spec for this kind requirements?

**Comment by jautor** [comment]
I don't think there's a good way to do this given the current support.  If there were a set of properties that all appear in one but not the other - you could use that as the "key" to create a Conditional Requirement like "If property X exists, then property Y must exist".  And then repeat that for "property Z, A, B, C..."
We certainly don't want you to tie things to string values like `Name`, or hard-coded `Id` values in URIs.  
If that doesn't work, we'll need to explore other options - we have avoided the complexity that comes with allowing requirements to reach outside of the individual resource, but this (and other cases) are certainly good rationale for doing that.

**Comment by JordanCHW** [comment]
Gotcha. Unfortunately, in our case we couldn't apply the alternative way you mentioned, because multiple loggers have overlap property requirements. Maybe we could fix the name of entries from certain logger type, then use the conditional requirement to obtain different requirement for different name. But in case we couldn't have the same name for different entry, I think we'll need the support of the hard-coded `Id` in URIs or SubordinateToResource.

**Comment by mraineri** [comment]
Closing since this is outside the scope of the profile specification. Since this request was made, there is now a "LogPurposes" property in LogService to help with this case, so you can key off of that property to control specific requirements.
