### ISSUE TITLE
Multiple condition AND?

### ISSUE THREAD

**Issue by JordanCHW** [DMTF/Redfish-Interop-Validator#155]
Is it possible to use AND in ConditionalRequirements for multiple contidions? For example, to mark a certain property's ReadRequirement as Mandatory when "SubordinateToResource = ..." AND "CompareProperty = ...". From current code it seems we can't do that, is there any alternatives? Or is it possible to extend the spec in the future?

**Comment by mraineri** [comment]
I suspect this is not supported in the Interop Profile Spec at this time since that could create very complicated profiles. @jautor does my assessment sound right to you?

If I am correct, we'll need to discuss this internally further.

**Comment by jautor** [comment]
@mraineri is correct - each ConditionalRequirement is intended to have a single condition.

**Comment by mraineri** [comment]
Closing; currently out of scope of the spec. If this capability is really needed, please bring this up internally to see if this something we'd like to add to the profile spec.
