### ISSUE TITLE
Overwrite MinCount in conditional requirement is not working

### ISSUE THREAD

**Issue by JordanCHW** [DMTF/Redfish-Interop-Validator#156]
Profile:

```
{
  ...
  "Resources": {
    "ProcessorCollection": {
      "Purpose": "Processor collection must contain 1 instance.",
      "PropertyRequirements": {
        "Members": {
          "MinCount": 1,
          "ReadRequirement": "Mandatory",
          "ConditionalRequirements": [
            {
              "Purpose": "Should contain at least 2 processor.",
              "SubordinateToResource": [
                "ComputerSystemCollection",
                "ComputerSystem"
              ],
              "MinCount": 2
            }
          ]
        }
      }
    }
  }
}

```

The validator should validate `/redfish/v1/Systems/system_x/Processors` with `MinCount = 2`, but it still validate with `MinCount = 1`. I added some logs and found that the condition is met as expected. 

The problem is
1. In the first round for validating `/redfish/v1/Systems/system_x/Processors`'s `Members` requirement, it enter https://github.com/DMTF/Redfish-Interop-Validator/blob/master/common/interop.py#L349 and validate the resource with `MinCount = 1`.
1. Then the validator iterate each resources under `Members` and validate each of them in https://github.com/DMTF/Redfish-Interop-Validator/blob/master/common/interop.py#L365
    *(Here's the problem, because the `rf_payload_item` is changed into each resource instead of the original `Members` array.)*
1. https://github.com/DMTF/Redfish-Interop-Validator/blob/master/common/interop.py#L393 -> The condition is met and recursively call `validatePropertyRequirement`, but the `rf_payload_item` is not the original `Members` array, the MinCount check won't apply.

Not sure what's the best solution to fix this issue based on current structure, looking forward to see if you have any ideas. Thanks!

**Comment by tomasg2012** [comment]
rf_payload_item is kind of tempermental to program around, and might be beneficial to remove passing around an object like this.   The design should switch to passing around the full payload and a JSON pointer path responsible for being validated.

Additionally, the profile can be preprocessed to generate tests for the URI path with each JSON pointer path, and not have to crawl through each option.

**Comment by JordanCHW** [comment]
> rf_payload_item is kind of tempermental to program around, and might be beneficial to remove passing around an object like this. The design should switch to passing around the full payload and a JSON pointer path responsible for being validated.
> 
> Additionally, the profile can be preprocessed to generate tests for the URI path with each JSON pointer path, and not have to crawl through each option. This should make it easier to iterate the types of tests needed and overwrite tests that are covered by a conditional.

Sounds good, but it seems a huge refactoring work, maybe we could create another issue to discuss about how to do that? I'd like to help if there's a clear design.

For this one, I think the main problem is the current logic expand the list property before checking conditional requirement, I created #156 to solve it with checking the conditonal requirements at the first. Could you help to review? Thanks!

**Comment by tomasg2012** [comment]
The logic in the PR seems sound, if it's just an error in order of operations.

**Comment by JordanCHW** [comment]
Agree, I think we could precompile each profile and coditionalrequirements overwrite at the first, but I think we don't need to compile all profiles into one, we may want to know a failed requirement come from which profile (current system does that).
