### ISSUE TITLE
Lots of Problems with Config and README

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Interop-Validator#16]
I had a lot of problems using the readme and setting up for execution. And then a quick exception. I will list problems here as encountered. 
1. Appears the program requires the profile to be listed on the command line. This is not shown in the readme. Appears need to specify the whole path? 
2. Is it possible to supply the profile in config file? Does not seem to work.
3. Does config file even work at all?  The options strings in the sample config file do not seem to match the strings in the source. I was not able to get anywhere with config file so I used command line.

For a profile I used https://github.com/DMTF/spmf/tree/master/profiles/RedfishInteroperabilityProfile.v1_0_0.json
The system used for test passes Redfish-Service-Validator with no errors

**Comment by jbobzin-insyde** [comment]
[Exception.txt](https://github.com/DMTF/Redfish-Interop-Validator/files/1347138/Exception.txt)
[ComplianceLog_10_01_2017_091313.txt](https://github.com/DMTF/Redfish-Interop-Validator/files/1347139/ComplianceLog_10_01_2017_091313.txt)

**Comment by tomasg2012** [comment]
The config file may have been updated in the Service Validator but not the Interop Validator.  Profiles also can only be specified thru command line, but it seems that it never was written about in the README, I assumed I put it in there...

However, it seems to be the case that you used the wrong file.  That is not a Profile, that is a Schema definition for a profile.  Using a Schema definition to verify a profile is optional, and can be specified in the command line with --schema (once again, for some reason it's not specified).

The profile intended to be used would be formatted like the one profiles/SampleProfile.json, but there are other spmf examples that can be used.

**Comment by jbobzin-insyde** [comment]
Thank you for explanation. I used BasicServerProfile.v0_91_0.json and got much better results.

System under test has 25 temperature sensors but none are named exactly 'CPU', 'Intake', or 'SystemBoard'. The error was reported 25 times. I can fix by sensor rename. But reporting on every temp item seems unnecessary. And I am guessing, that if I did the rename, I would still get an error on the other 22? Please check logic.

**Comment by tomasg2012** [comment]
I found this profile ( https://github.com/DMTF/spmf/blob/basic-profile/profiles/BasicServerProfile.v1_0.json ) and looked for the pattern you're noticing:

```
				"Temperatures": {
					"ReadRequirement": "Mandatory",
					"MinCount": 3,
					"PropertyRequirements": {
						"ReadingCelsius": {},
						"PhysicalContext": {
							"Comparison": "AllOf",
							"Values": ["CPU", "Intake", "SystemBoard"]
						},
						"UpperThresholdFatal": {
							"ReadRequirement": "Recommended"
						},
						"UpperThresholdCritical": {
							"ReadRequirement": "Recommended"
						},
						"UpperThresholdNonCritical": {
							"ReadRequirement": "Recommended"
						},
						"Status": {}
					}
				},
```

From my understanding of the above, for the PhysicalContext enumeration/string value, it requires that All Of these variations exist in the system.  So there must be at least one Temperature monitor for the CPU, Intake, and SystemBoard, which requires a minimum count of 3 Temperature monitors.  Does this sound right?  In the program, if it finds any sort of List object (Temperatures) with a Comparison test, it checks every item and checks off the ones that it finds.

**Comment by jbobzin-insyde** [comment]
I agree this is an error, I was complaining that it was reported 25 times.

Does the mockup you tested against have additional temperature items in the array beyond the 3 required temperatures? Suggest test the case of one or more required are missing to see how many errors are reported.

**Comment by tomasg2012** [comment]
Oh, I apologize, I missed the point.  Could you provide a log?  I wasn't aware of it being reported multiple times, maybe it's because the mockups I've been using only have a single Temperature sensor or type of sensor.

**Comment by jbobzin-insyde** [comment]
[logs.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/1347388/logs.zip)

**Comment by tomasg2012** [comment]
The README had a small problem with Markdown formatting, which axed the text '<payload>' from rendering as normal text.  It has been changed.  However, it is true that the profile can only be specified via the command line.  The way the config file is handled in the program will be changed, however, but as it is it should work?

I am reviewing the log with another to see if it is wrong or not, in my first impression it looks like PhysicalContext is missing in your payload?  I don't see how that isn't an error that should be reported...

**Comment by jbobzin-insyde** [comment]
That is an answer I can understand and accept.
