### ISSUE TITLE
Check ALLOW header as an indication of `WriteRequirement` pass/fail

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Interop-Validator#169]
While the tool does not perform any PATCH operations (non-destructive testing), it could give some indication, mostly negative testing, if a `WriteRequirement` will not pass.

Checking the ALLOW header for PATCH support on a resource with any `WriteRequirement` would at least indicate that the service claims support (or not).  If the resource doesn't support PATCH, then obviously any write requirements will fail.  While the opposite is not true, this is at least an improvement in coverage.

**Comment by mraineri** [comment]
Change added
