### ISSUE TITLE
Would this be useful feature - config to report mandatory only, or mandatory plus recommended

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Interop-Validator#17]
Suggest - add new config to report violations on mandatory only, or alternatively mandatory plus recommended

**Comment by mraineri** [comment]
Maybe not change it to a "fail", but rather make it a "warning" or something else less incriminating...

**Comment by jbobzin-insyde** [comment]
SPMF is trying to approve profile. It was discussed on Tuesday If this enhancement could be accelerated it would help that process.

**Comment by jbobzin-insyde** [comment]
[BasicServerProfile.v1_0.json.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/1392337/BasicServerProfile.v1_0.json.zip)
here is the latest draft profile

**Comment by jbobzin-insyde** [comment]
Could Tomas throw this together? Discuss Thursday?

**Comment by tomasg2012** [comment]
Yessir.  I'll make sure this profile works and that this feature is available.

**Comment by tomasg2012** [comment]
Unusually, the profile provided in this example seems wrong, as one of the Comparison blocks uses the term Values instead of ComparisonValues as defined in the markdown describing the term.

Except, it still passes the Schema check built into the program... will have to ask more about this.

**Comment by jbobzin-insyde** [comment]
I think it is possible you are looking at old version of the markdown. 
This version in branch basic-server-profiles was last edited 10/10 :

https://github.com/DMTF/spmf/blob/basic-server-profile/profiles/Redfish%20Interoperability%20Profiles.md 

Can you reconfirm and post in a new issue?

**Comment by tomasg2012** [comment]
Ah, of course, this seems to be it's own issue, that the tool needs to be updated to the latest definitions of profiles.

**Comment by tomasg2012** [comment]
However, in spirit of the observation, line 105 of that current iteration of BasicServerProfile.v1_0.json does infact have an erroneous keyword, at least, I believe:

```
				"IndicatorLED": {
					"ReadRequirement": "Recommended",
					"ConditionalRequirements": [{
						"Purpose": "Physical Systems must have a writable Indicator LED",
						"CompareProperty": "SystemType",
						"Comparison": "AnyOf",
						"Values": ["Physical"],
						"ReadRequirement": "Mandatory",
						"WriteRequirement": "Mandatory"
					}]
				},
```

Will have to mention tomorrow, that Values should be ComparisonValues.

**Comment by mraineri** [comment]
Fixed in latest PR
