### ISSUE TITLE
Chassis resource fail errors

### ISSUE THREAD

**Issue by plmanik** [DMTF/Redfish-Interop-Validator#177]
Hi,
I'm confused about interpreting Redfish-Interop-Validator report related to Chassis resource
Tool Version: 2.1.3
Run against OCPServerHardwareManagement.v1_0_0.json

I'm able to see Chassis under /redfish/v1

{
    "@odata.id": "/redfish/v1",
    "@odata.type": "#ServiceRoot.v1_15_0.ServiceRoot",
    "AccountService": {
        "@odata.id": "/redfish/v1/AccountService"
    },
        "CertificateService": {
        "@odata.id": "/redfish/v1/CertificateService"
    },
    "Chassis": {
        "@odata.id": "/redfish/v1/Chassis"
    },
	
	
Able to see Chassis collection
{
    "@odata.id": "/redfish/v1/Chassis",
    "@odata.type": "#ChassisCollection.ChassisCollection",
    "Members": [
        {
            "@odata.id": "/redfish/v1/Chassis/AC_Baseboard"
        }
    ],
    "Members@odata.count": 1,
    "Name": "Chassis Collection"
}

For above response getting below errors

Chassis collection resource availabl in Serviceroot, Chassis instance available as /redfish/v1/Chassis/AC_Baseboard, but getting error as DNE
Service Level Requirements
fail.Chassis.ReadRequirement: 2

Property Name												        Value		Expected	    Actual	      Result
Chassis.ReadRequirement										       Mandatory	Must Exist	DNE		FAIL
OCPBaselineHardwareManagement -- Chassis.ReadRequirement	                       Mandatory	Must Exist	DNE		FAIL

Same error passed in Serviceroot OCPBaselineHardwareManagement -- Chassis.ReadRequirement
/redfish/v1/(response time: 0)ServiceRoot
Property Name												Value		Expected	      Actual	Result
OCPBaselineHardwareManagement -- Chassis.ReadRequirement	                Mandatory	Must Exist	Exists	PASS

Able to see Members@odata.count": 1 in response, but showing below error
/redfish/v1/Chassis(response time: )
Property Name										Value	Expected	     Actual	        Result
OCPBaselineHardwareManagement -- Members. MinCount	         1		<=			0		FAIL

Is it possible to print response(Show Payload) like Service validator to see whether redfish response is correct or not
Please explain about understanding above failure case

Thanks,
Mani

**Comment by mraineri** [comment]
Please provide the HTML report and the debug txt file.

**Comment by mraineri** [comment]
Closing; no further info provided to help with the issue.
