### ISSUE TITLE
Use `@Redfish.WriteableProperties` to valiate `WriteRequirement`

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Interop-Validator#178]
While the tool is unable to verify that individual properties can be PATCHed (non-destructive testing), we can use `@Redfish.WriteableProperties` annotation values to validate those requirements.

Like with #169 we can use the protocol and annotations as indicators of PATCH support.  If the service supports the `@Redfish.WriteableProperties` annotation, and it is present in the resource payload, any properties listed as values would meet a `WriteRequirement`.  Any properties not listed would fail those write requirements.  

If the annotation is not present, then this check is not used, and the write requirements are simply not tested, as is done today.

**Comment by plmanik** [comment]
@mraineri Can we get some mockup example for usage of @Redfish.WriteableProperties annotation, if we are not returning @Redfish.WriteableProperties annotation in get response, Redfish-Interop-Validator is skipping Patch and showing as NOT TESTED
