### ISSUE TITLE
JSON Pointer syntax works for 'CompareProperty' but not 'UseCaseKeyProperty'

### ISSUE THREAD

**Issue by linchrislin** [DMTF/Redfish-Interop-Validator#179]
Practiced 2 profiles with JSON pointer applied to CompareProperty of ConditionalRequirements in one profile and UseCaseKeyProperty of UseCases in another. Running the 2 profiles with same resource payload, the out log is as expectation for the Conditional implementation, but looks strange for the UseCase implementation.

Plz have profiles / payload / out-logs in [JptrTests.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/12735174/JptrTests.zip)

**Comment by mraineri** [comment]
The spec actually doesn't call out the usage of JSON pointers for UseCaseKeyProperty today; normally when JSON pointers are allowed, we specify that directly in the definition of the property. For example, we have this defined for "CompareProperty":

> If the value begins with a / character, the value shall represent an RFC6901-defined JSON Pointer, specifying an explicit path from the root level of the resource to a property within the resource.

But no such text for UseCaseKeyProperty...

**Comment by linchrislin** [comment]
Understood it's not stated in the spec and is not supported in present. 
It would be helpful when user try to create the use cases of:
  - EmbeddedMemory
  - AbsentDrive
  ..., etc.

**Comment by mraineri** [comment]
Closing; the profile spec has already gone in the direction of adding UseCaseType values to help constrain how use cases are defined.
