### ISSUE TITLE
Value Comparison is not checked in ConditionalRequirements

### ISSUE THREAD

**Issue by linchrislin** [DMTF/Redfish-Interop-Validator#180]
Practiced a profile similar to 8.4.3.5.4 Example in [DSP0272_1.6.0.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0272_1.6.0.pdf), it's expecting: *If the PizzaType property is not equal to Cheese , then the Pepperoni property becomes both mandatory and must have a value of true.*
but got: If the PizzaType property is not equal to Cheese , then the Pepperoni property becomes mandatory **without comparing the** value of true.
See profile statement and result log:
![image](https://github.com/DMTF/Redfish-Interop-Validator/assets/20431127/0f9ae188-8795-4624-9842-5f18112a1d42)
![image](https://github.com/DMTF/Redfish-Interop-Validator/assets/20431127/5141c1a6-f398-46f7-9f76-48d4b8380668)

**Comment by mraineri** [comment]
@linchrislin Can you please provide the contents of the response payload for this resource? I'm assuming based on the "Expected" column there isn't a check being performed on EncryptionStatus (beyond the "Exists" check), but I'd like to line it up before I start debugging this.

**Comment by linchrislin** [comment]
@mraineri Attach the response resource payload and HTTP header to [Drive0.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/12773473/Drive0.zip).
Be noticed that EncryptionStatus is type of String instead of Boolean, and still get same result when comparing to value of 'StringText'.

**Comment by mraineri** [comment]
Thanks! I'll use these for test cases when debugging
