### ISSUE TITLE
Need ability to parse wildcards

### ISSUE THREAD

**Issue by MeritedHobbit** [DMTF/Redfish-Interop-Validator#182]
We need to permit wildcard which can hold a list of strings. The expectation is for the interop validator to validate the profile defined properties/trees against all the values held by wildcard.
The profile itself should permit housing this wildcard for eg.
<Chassis_ID>: {
               PropertyRequirements:....

**Comment by mraineri** [comment]
That's currently not permitted by the Redfish Interoperability Profile Specification. Unfortunately we can't make changes to the tool that go outside the scope of the spec.

**Comment by mraineri** [comment]
Closing since this is not allowed by the profile spec today. If we still need this type of feature, please bring this up in the main forum.
