### ISSUE TITLE
Physicalcontext comparison error

### ISSUE THREAD

**Issue by plmanik** [DMTF/Redfish-Interop-Validator#185]
Hi,
I'm getting error as **fail.Comparison.Thermal.Temperatures.PhysicalContext: 1**
<html>
<body>

Comparison.Thermal.Temperatures.PhysicalContext | AllOf | ['CPU', 'Intake', 'SystemBoard'] | ['Intake', 'Intake', 'Intake', 'Intake', 'Intake', 'Intake', 'Intake'] | FAIL
-- | -- | -- | -- | --

</body>
</html>
Response coming as intake only, but it's failing, checked debug log also and it's correct.  Copied debug print, response please confirm if response is correct or anything required to change in response 

**DEBUG - inside complex Temperatures#0.PhysicalContext
DEBUG - propRequirement with value: Intake
DEBUG - Testing ReadRequirement 
	expected:Mandatory, exists: True
DEBUG - 	pass True
VERBOSE1 - Testing a comparison 
	('Intake', 'AllOf', ['CPU', 'Intake', 'SystemBoard'])
DEBUG - 	pass False**

Get response for reference
"Temperatures": [
        {
            "@odata.id": "/redfish/v1/Chassis/Self/Thermal#/Temperatures/0",
            "LowerThresholdCritical": 0,
            "LowerThresholdNonCritical": 5,
            "MemberId": "0",
            "Name": "RR_Brd Temp 1",
            "Oem": {
                "Ami": {
                    "@odata.type": "#AMIChassisPowerThermal.v1_0_0.AMIChassisPowerThermal",
                    "OwnerLUN": 0
                }
            },
            "PhysicalContext": "Intake",
            "ReadingCelsius": 22,
            "RelatedItem@odata.count": 0,
            "SensorNumber": 60,
            "Status": {
                "Health": "OK",
                "State": "Enabled"
            },
            "UpperThresholdCritical": 37,
            "UpperThresholdNonCritical": 32
        },

Thanks,
Mani

**Comment by mraineri** [comment]
That error is correct. The usage of "AllOf" means that across all of the PhysicalContext properties in Thermal/Temperatures you need to have all of the listed values. Your service only contains "Intake" and is missing "SystemBoard" and "CPU".

**Comment by plmanik** [comment]
Thanks for immediate reply, you meant to say we need to have all values in one sensor or in different sensor.
I hope we can associate onlt one value to physicalcontext and Example response from DSP2046 contains only one value as chassis

{ "@odata.type": "#Sensor.v1_2_0.Sensor", "Id": "CabinetTemp", "Name": "Rack Temperature", "ReadingType": "Temperature", "ReadingTime": "2019-12-25T04:14:33+06:00", "Status": { "State": "Enabled", "Health": "OK" }, "Reading": 31.6, "ReadingUnits": "C", "ReadingRangeMin": 0, "ReadingRangeMax": 70, "Accuracy": 0.25, "Precision": 1, "SensingInterval": "PT3S", **"PhysicalContext": "Chassis"**, "Thresholds": { "UpperCritical": { "Reading": 40, "Activation": "Increasing" }, "UpperCaution": { "Reading": 35, "Activation": "Increasing" }, "LowerCaution": { "Reading": 10, "Activation": "Increasing" } }, "Oem": {}, "@odata.id": "/redfish/v1/Chassis/1/Sensors/CabinetTemp"

Thanks,
Mani

**Comment by mraineri** [comment]
They would be in different resources/temperature objects. Since the requirement is around the "Thermal" resource's Temperatures array, it wouldn't involve Sensor resources. But, if you had the following...

* `/redfish/v1/Chassis/Self/Thermal#/Temperatures/0` contains `Intake` for `PhysicalContext`.
* `/redfish/v1/Chassis/Self/Thermal#/Temperatures/3` contains `SystemBoard` for `PhysicalContext`.
* `/redfish/v1/Chassis/Self/Thermal#/Temperatures/5` contains `CPU` for `PhysicalContext`.

... the three above together satisfies that requirement. Some of the comparison checks are "service-wide", meaning it will use the values from the same property across all instances of the object/resource in the service.

There could be a similar requirement on Sensor, where if you had the following...

* `/redfish/v1/Chassis/Self/Sensors/InletTemperature contains `Intake` for `PhysicalContext`.
* `/redfish/v1/Chassis/Self/Sensors/BoardTemperature` contains `SystemBoard` for `PhysicalContext`.
* `/redfish/v1/Chassis/Self/Sensors/CPU1Temp` contains `CPU` for `PhysicalContext`.

... you would then satisfy that type of requirement as well.

**Comment by plmanik** [comment]
Got your point and thanks for explaination. How we can confirm whether it's "service-wide. As per https://github.com/opencomputeproject/HWMgmt-OCP-Profiles/blob/master/HWMgmt/OCPBaselineHardwareManagement.v1_0_2.json

"EthernetInterface": {
			"MinVersion": "1.1.0",
			"ReadRequirement": "Recommended",
			"ConditionalRequirements": [{
				**"SubordinateToResource": ["Manager", "EthernetInterfaceCollection"],**
				"ReadRequirement": "Mandatory"
			}],
As per this interop validator needs to validate Manager EthernetInterface, but it's checking Systems Instance also and showing error in report. Is this behaviour correct?

/redfish/v1/Systems/Self/EthernetInterfaces/EthernetInterface0
(response time: 0)
Show Results	Context: /redfish/v1/$metadata#EthernetInterface.EthernetInterface
File Origin: None
Resource Type: #EthernetInterface.v1_6_2.EthernetInterface	GET Success	
fail.SpeedMbps.ReadRequirement: 1
pass: 30
passGet: 1
totaltests: 31


INFO - *** /redfish/v1/Systems/Self/EthernetInterfaces/EthernetInterface0, EthernetInterface
DEBUG - *** None, False, False
INFO - 	 Type (#EthernetInterface.v1_6_2.EthernetInterface), GET SUCCESS (time: 0)
INFO - ### Validating an InteropResource
DEBUG - {'MinVersion': '1.1.0', 'ReadRequirement': 'Recommended', 'PropertyRequirements': {'MACAddress': {}, 'SpeedMbps': {}, 'InterfaceEnabled': {}, 'LinkStatus': {}, 'Status': {'PropertyRequirements': {'Health': {}, 'State': {}}}, 'HostName': {}, 'FQDN': {}, 'NameServers': {}, 'IPv4Addresses': {'PropertyRequirements': {'Address': {}, 'SubnetMask': {}, 'AddressOrigin': {}, 'Gateway': {}}}}}
DEBUG - Testing minVersion 
	('#EthernetInterface.v1_6_2.EthernetInterface', '1.1.0')
DEBUG - 	pass True
INFO - ### Validating PropertyRequirements for MACAddress
DEBUG - there are no requirements for this prop
DEBUG - Testing ReadRequirement 
	expected:Mandatory, exists: True
DEBUG - 	pass True
INFO - ### Validating PropertyRequirements for SpeedMbps
DEBUG - there are no requirements for this prop
DEBUG - Testing ReadRequirement 
	expected:Mandatory, exists: False
DEBUG - 	pass False

Thanks,
Mani

**Comment by mraineri** [comment]
That's a function of the Redfish Interop Profile Spec (DSP0272).

@jautor I'm looking at the "Comparison" clause of the spec, and from reading it, it's not clear to me that the intent of AnyOf and AllOf comparisons are service-wide. Is there somewhere else this is called out specifically?

**Comment by plmanik** [comment]
As per DSP0272_1.6.0.pdf, based on  Parent and subordinate resources, it needs to check only Manager resource only ("SubordinateToResource": ["Manager", "EthernetInterfaceCollection"],), please correct me if my understanding is incorrect.

As you said allof, anyof is not very clear in DSP0272_1.6.0.pdf (section 8.4.3.2 Comparison) and it's telling atleast **At least one instance of the property in this resource** , in this example it's covered in 3 temperature array

**8.4.3.5.1 Parent and subordinate resources
Because there can be several instances of a particular Redfish schema in the resource tree, the
requirements placed on those resources may vary depending on their usage. Since the profile is
schema-centric, the SubordinateToResource function allows a profile to specify requirements based a
resource instance's placement in the resource tree.
SubordinateToResource allows specifying the schema (resource) path from parent resources to the
resource to which the requirements apply. This property contains an array of schema names, in the
top-down order that they appear in the path to the required resource.
Note that this functionality may also be accomplished using the URIs function for the resource, which
is the preferred method.
8.4.3.5.2 Example
For the property HostName in the EthernetInterface schema, the example shows it as Recommended
property. But if an instance of EthernetInterface is linked from a ComputerSystem resource, through the
EthernetInterfaceCollection resource, the Condition is met, which changes the HostName property
requirement to Mandatory .**

**Comment by mraineri** [comment]
The parent/subordinate too statements are orthogonal to this. That's to strictly narrow down the scope of testing to particular resource instances (such as only applying the requirements to the /redfish/v1/Managers hierarchy). You could use AllOf and AnyOf to perform testing strictly on that one tree, but the usage in the OCP profile doesn't narrow the scope like this.

**Comment by plmanik** [comment]
The parent/subordinate too statements are orthogonal to this. That's to strictly narrow down the scope of testing to particular resource instances (such as only applying the requirements to the /redfish/v1/Managers hierarchy) - This means it needs to test only manager resource only? But errors were reported from Computersystem resources also which is incorrect and manager resource ethernetinterface testing is passed

**Comment by mraineri** [comment]
That's an entirely different error and is not using the AnyOf/AllOf construct from the original issue posted.

The first conditional requirement found at line 70 elevates the resource's requirement to mandatory for EthernetInterface resources beneath a Manager, whereas the default requirement is just a recommendation. However, since the resource exists beneath "Systems", it must pass the property requirements called out in the profile. "SpeedMbps" is called out as a mandatory property, regardless of its location, meaning if you've implemented EthernetInterface beneath Systems, it's required. However, other properties, like "HostName", are conditional; they're only required if used under a Manager resource.

**Comment by plmanik** [comment]
Thanks for reply, Please close this issue once concluded for Allof comparison in document

**Comment by mraineri** [comment]
Closing; the current profiles from OCP (https://github.com/opencomputeproject/HWMgmt-OCP-Profiles) require CPU, Intake, and SystemBoard temperatures. The error from the tool is correct.
