### ISSUE TITLE
--schema and --required_profiles_dir argument usage confirm

### ISSUE THREAD

**Issue by Againxarcher** [DMTF/Redfish-Interop-Validator#186]
Hi,

Below are the config file and profile that I used for running the Interop Validator.
[interop_file.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/13294158/interop_file.zip)

And here is my command for running the tool.
It looks working and running successfully.
> python3 RedfishInteropValidator.py -c ./config/grace_config.ini ./profile/OCPServerHardwareManagement.v1_0_1.json

But I still would like to know how to use --schema and --required_profiles_dir.
As i know the schema should download from here.
![image](https://github.com/DMTF/Redfish-Interop-Validator/assets/147082751/637de2dc-2ace-48e3-b6c5-08e601997a90)

For --schema, is this for check the profile format?
For --required_profiles_dir, is this will be run with multiple profiles?

And also have one more question for argument "online_profiles". 
As my understanding, this will download the profile from internet.
If so, how it works? How do I know the profile is suitable for our service?

**Comment by mraineri** [comment]
Yes, `--schema` is used to check that the profile meets the schema definition for profiles. You would point it to a JSON file found in that 8013 file (such as RedfishInteroperabilityProfile.v1_6_0.json).

Yes, `--required_profiles_dir` is used with you have multiple profiles in question. More specifically, if you have one profile that is including other profiles with the `RequiredProfiles` term, and those profiles are in a different directory, you would use this argument to let the tool know where to get these referenced profiles.

The intent of `online_profiles` is to let the tool know if it can download profiles remotely or if it should prefer a local copy. The `RequiredProfiles` term can contain durable URIs to referenced profiles (the `Repository` term contains the URI), and if this argument is set to true, the tool can download the profile from the referenced URI. However, this may not work as expected today; there's an older issue (#109) regarding this.

**Comment by mraineri** [comment]
Closing; no follow-up questions regarding this subject
