### ISSUE TITLE
False positive results when "Recommended" or "IfImplemented" object does not exist.

### ISSUE THREAD

**Issue by lukkldzse** [DMTF/Redfish-Interop-Validator#189]
Hello,

In test report I can see that unexisting resources/properties that are 'Recommended' or 'IfImplemented'  have a status: PASS.
It gives a false view on the status of service implementation
From my perspective, if the object is not Mandatory and does not exist, then test should has a status: Not Applicable (NA)
(This issue was discussed also on redfishforum: https://redfishforum.com/thread/989/interop-validator-false-positive-results )

Example:
![screen1](https://github.com/DMTF/Redfish-Interop-Validator/assets/154233242/4093d691-6d63-4a1c-9e9e-6477c1f8e594)

**Comment by mraineri** [comment]
PR merged
