### ISSUE TITLE
To me, it seems pull request #19 broke the tool

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Interop-Validator#20]
I am not seeing the output that was produced by earlier versions. For example, When tool finds EthernetInterface object tool used to check the presence of the listed PropertyRequirements inside. This no longer happens.

**Comment by jbobzin-insyde** [comment]
[ConformanceLog_10_05_2017_174055.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/1362843/ConformanceLog_10_05_2017_174055.zip)
[ConformanceHtmlLog_10_05_2017_174055.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/1362844/ConformanceHtmlLog_10_05_2017_174055.zip)

**Comment by tomasg2012** [comment]
Unusual that less tests seem to be happening, but I don't think it's a result of the new pull or the system being tested on?  I gave it a shot and the tests are the same...  

The diffs between each PR don't show enough change to expect completely new behavior, except for changing blank string '' to 'DNE on Line 283 which seems unrelated, but has potential consequences...  I think the tool itself has just had a runtime problem that hadn't been found yet, maybe with the ordering of dictionary items?

One thing the that is overlooked is that it doesn't printout the profile used in each run of the tool, or what OS the tool is running on.  Perhaps different versions were used?  Based on debug log printouts

```
INFO - EthernetInterface
INFO - ### Validating an InteropResource
DEBUG - {'ReadRequirement': 'Recommended', 'PropertyRequirements': {'IPv6StaticAddresses': {'ReadRequirement': 'Recommended'}, 'IPv4Addresses': {'ConditionalRequirements': [{'WriteRequirement': 'Mandatory', 'SubordinateToResource': ['Manager', 'EthernetInterfaceCollection'], 'ReadRequirement': 'Mandatory'}], 'PropertyRequirements': {'Address': {}, 'SubnetMask': {}, 'AddressOrigin': {}, 'Gateway': {}}, 'ReadRequirement': 'Recommended'}, 'IPv6Addresses': {'PropertyRequirements': {'Address': {}, 'AddressState': {}, 'AddressOrigin': {}, 'PrefixLength': {}}, 'ReadRequirement': 'Recommended'}, 'LinkStatus': {}, 'IPv6AddressPolicyTable': {'ReadRequirement': 'Recommended'}, 'HostName': {'ConditionalRequirements': [{'WriteRequirement': 'Mandatory', 'SubordinateToResource': ['Manager', 'EthernetInterfaceCollection'], 'ReadRequirement': 'Mandatory'}], 'ReadRequirement': 'Recommended'}, 'SpeedMbps': {}, 'NameServers': {'ConditionalRequirements': [{'WriteRequirement': 'Mandatory', 'SubordinateToResource': ['Manager', 'EthernetInterfaceCollection'], 'ReadRequirement': 'Mandatory'}], 'ReadRequirement': 'Recommended'}, 'InterfaceEnabled': {}, 'FQDN': {'ConditionalRequirements': [{'WriteRequirement': 'Mandatory', 'SubordinateToResource': ['Manager', 'EthernetInterfaceCollection'], 'ReadRequirement': 'Mandatory'}], 'ReadRequirement': 'Recommended'}, 'Status': {'PropertyRequirements': {'State': {}, 'Health': {}}}, 'MACAddress': {}}, 'MinVersion': '1.1.0', 'ConditionalRequirementss': [{'SubordinateToResource': ['Manager', 'EthernetInterfaceCollection'], 'ReadRequirement': 'Mandatory'}]}
```


```
DEBUG - {'PropertyRequirements': {'IPv6AddressPolicyTable': {}, 'IPv4Addresses': {'PropertyRequirements': {'SubnetMask': {}, 'Gateway': {}, 'Address': {}, 'AddressOrigin': {}}}, 'FQDN': {}, 'IPv6StaticAddresses': {}, 'InterfaceEnabled': {}, 'NameServers': {}, 'LinkStatus': {}, 'SpeedMbps': {}, 'IPv6Addresses': {'PropertyRequirements': {'AddressOrigin': {}, 'PrefixLength': {}, 'Address': {}, 'AddressState': {}}}, 'HostName': {}, 'MACAddress': {}, 'Status': {'PropertyRequirements': {'State': {}, 'Health': {}}}}, 'ReadRequirement': 'Recommended', 'MinVersion': '1.1.0'}
```

**Comment by jbobzin-insyde** [comment]
[OCPBasicServer.v1_0.json.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/1363234/OCPBasicServer.v1_0.json.zip)

Attached is the latest version of OCP profile captured from the branch

**Comment by tomasg2012** [comment]
For context, I was comparing logs between both issues that were submitted this week, my bad.  But in this instance, I don't believe execution has changed, I believe different profiles might've been used, one being `OcpBasicServer.v1_0` while the other used was `BasicServerProfile`

**Comment by jbobzin-insyde** [comment]
So the difference in results arises from the latest draft OCP profile. Can you review the profile and determine if the results are correct?

**Comment by tomasg2012** [comment]
Closed, will be reviewed in process supporting 1.0.0.
