### ISSUE TITLE
Interop Validator is throwing error for write requirement for Readonly URI

### ISSUE THREAD

**Issue by manipk01** [DMTF/Redfish-Interop-Validator#202]
Hi @mraineri ,

When using the latest version write requirement issue is coming in the readonly URI.

ERROR - PATCH in Allow header not available, property is not writeable Mandatory

URI: /redfish/v1/Managers/{{instance}}/EthernetInterfaces/usb0
 
<img width="707" alt="Screenshot 2024-04-05 124222" src="https://github.com/DMTF/Redfish-Interop-Validator/assets/124661726/37a0b1b2-8883-4dbd-8f96-1c90cf98a94d">

For the URI **/redfish/v1/Managers/{{instance}}/EthernetInterfaces/usb0**(Logical EthernetInterface resource) we have implemented all properties under this URI as not writable. So whether any exception will be made from tool side?

Note: Already this issue is mentioned in the Issue(https://github.com/DMTF/Redfish-Interop-Validator/issues/200) but still it is coming with the latest fix.
 
Thanks,
Mani P K

**Comment by mraineri** [comment]
No, that's a real error. OCP's profile dictates that those are writable.

**Comment by mraineri** [comment]
Closing; this is correct behavior based on the OCP profiles published today.
