### ISSUE TITLE
Update tool to support current profile "release" 1.0.0

### ISSUE THREAD

**Issue by tomasg2012** [DMTF/Redfish-Interop-Validator#22]
In private repo DMTF/spmf, information regarding Interop Profiles has been updated to 1.0.0, is necessary to update functionality to match the keywords added and changed.

**Comment by mraineri** [comment]
Assigning to @tomasg2012 to work on

**Comment by mraineri** [comment]
Latest PR brings the tool up to the 1.0.0 level of the spec; closing
