### ISSUE TITLE
-Help command has confusing parameter definitions

### ISSUE THREAD

**Issue by Seretsi** [DMTF/Redfish-Interop-Validator#3]
Hello all,

On running "python3 RedFishInteropValidator.py -h" the help text is return as usual. I noticed that the definitions returned for the positional arg "_profile_" and the optional args "_suffix_" and "_schema_" the same. The definition reads "_suffix of local schema files (for version differences)_".

Can I get some clarity for these three args?

**Comment by tomasg2012** [comment]
My apologies, the power of copy-paste is has its drawbacks.

_profile_ is the json file that corresponds to the interop profile you wish to validate a service against, while _schema_ is an optional argument that would allow you to validate the _profile_ itself, whether it is correct/conformant with expected Redfish profiles.

_suffix_ is a backup optional argument for metadata stored on your harddrive when traversing services, such as ServiceRoot__v1.xml_, where the latter portion of the CSDL filename is written.  The program will normally derive this from the service's $metadata references, if possible.

**Comment by Seretsi** [comment]
Thanks a lot. I definitely know how that goes.
