### ISSUE TITLE
Tool should allow any profile version

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/Redfish-Interop-Validator#38]
The tool does not look for any profile with version less than v1.0.0,

The tool should be able to read a profile with any version.  In the OCP case, the baseline and server (which references the baseline) profiles may both be in draft (<1.0.0), prior to OCP approval.

If the desire is the restrict versions to => 1.0.0 for "official" conformance runs, then I would suggest a flag in the config.ini file (e.g. OfficialTest = True)

**Comment by tomasg2012** [comment]
Should be fixed, but warns that '1.0.0' is the default minversion.

**Comment by tomasg2012** [comment]
Closed with latest PR.
