### ISSUE TITLE
The log file should include name of Profile file used

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/Redfish-Interop-Validator#42]
The log file should include the name of the Profile file read as input, and all referenced Profile files.

Extra credit would be a hash for each Profile file.  Then the Profile own could determine that their Profile files had not been altered, prior to the execution run.

**Comment by jcleung5549** [comment]
From Bill Carter (OCP CTO): "I would like to know that the correct config files was used and there wasn’t a ‘cheat’ run performed."

**Comment by tomasg2012** [comment]
Ah of course, from the email I overlooked that the profile is not included in the config.  Will do.

**Comment by mraineri** [comment]
Merged in latest PR
