### ISSUE TITLE
Exceptions in execution of InteropValidator

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Interop-Validator#46]
There are a number of Tracebacks in the attached log.
I only looked at the 1st one in which decodeditem is a string,
    not a list or a dict and can't see how "item" could have been created.
Anyway could someone tack a look at the exceptions?
python3 RedfishInteropValidator.py  -c ./config.ini OCPBaselineHardwareManagement.v0_2_1.json
The target service is the Reddrum front end with obmc backend.
Thanks
[log5.txt](https://github.com/DMTF/Redfish-Interop-Validator/files/2224108/log5.txt)

**Comment by tomasg2012** [comment]
The decodeditem issue needs to be fixed, but the latter issue is a piece of code I don't believe has changed recently, and I'm curious as to why it's tripping up like that.  Does this happen on the Service-Validator as well?

**Comment by PhillipWatts1012** [comment]
Not that I am aware of. Our test people run the Service Validator

as do I somtimes.

________________________________

**Comment by tomasg2012** [comment]
It just occurred to me, I don't believe having named fragments like above is a valid way to create your fragments, as it's having trouble dereferencing something that is expected to be a list.  I may be mistaken, would you be able to post your Thermal payload, with the Temperatures involved?

**Comment by PhillipWatts1012** [comment]
I assume you are referring to the 2nd Traceback

A problem when getting resource has occurred /redfish/v1/Chassis/1/Thermal#/Temperatures/CPU1
output:
Traceback (most recent call last):


[dmtf@laptop01 Redfish-Interop-Validator]$ rfgr /redfish/v1/Chassis/1/Thermal#/Temperatures/CPU1
++ redfishtool -r localhost -u root -p password raw GET /redfish/v1/Chassis/1/Thermal#/Temperatures/CPU1
{
    "Description": "Thermal Resource for the chassis (Fans, TempSensors)",
    "Redundancy": [
        {
            "MinNumNeeded": 5,
            "Mode": "N+m",
            "MemberId": "0",
            "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Redundancy/0",
            "RedundancySet": [
                {
                    "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Fans/3"
                },
                {
                    "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Fans/5"
                },
                {
                    "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Fans/0"
                },
                {
                    "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Fans/4"
                },
                {
                    "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Fans/2"
                },
                {
                    "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Fans/1"
                }
            ],
            "Status": {
                "Health": "OK",
                "State": "Enabled"
            },
            "Name": "Shared Chassis Fans",
            "MaxNumSupported": 6
        }
    ],
    "Fans": [
        {
            "PhysicalContext": "Backplane",
            "LowerThresholdCritical": 16,
            "Reading": 2233,
            "Redundancy": [
                {
                    "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Redundancy/0"
                }
            ],
            "MinReadingRange": 0,
            "MaxReadingRange": 2500,
            "MemberId": "3",
            "ReadingUnits": "RPM",
            "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Fans/3",
            "Status": {
                "Health": "OK",
                "State": "Enabled"
            },
            "Name": "Fan3",
            "FanName": "Fan3"
        },
        {
            "PhysicalContext": "Backplane",
            "LowerThresholdCritical": null,
            "Reading": 2233,
            "Redundancy": [
                {
                    "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Redundancy/0"
                }
            ],
            "MinReadingRange": null,
            "MaxReadingRange": null,
            "MemberId": "5",
            "ReadingUnits": "RPM",
            "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Fans/5",
            "Status": {
                "Health": "OK",
                "State": "Enabled"
            },
            "Name": "Fan5",
            "FanName": "Fan5"
        },
        {
            "PhysicalContext": "Backplane",
            "LowerThresholdCritical": null,
            "Reading": 2233,
            "Redundancy": [
                {
                    "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Redundancy/0"
                }
            ],
            "MinReadingRange": null,
            "MaxReadingRange": null,
            "MemberId": "0",
            "ReadingUnits": "RPM",
            "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Fans/0",
            "Status": {
                "Health": "OK",
                "State": "Enabled"
            },
            "Name": "Fan0",
            "FanName": "Fan0"
        },
        {
            "PhysicalContext": "Backplane",
            "LowerThresholdCritical": null,
            "Reading": 2233,
            "Redundancy": [
                {
                    "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Redundancy/0"
                }
            ],
            "MinReadingRange": null,
            "MaxReadingRange": null,
            "MemberId": "4",
            "ReadingUnits": "RPM",
            "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Fans/4",
            "Status": {
                "Health": "OK",
                "State": "Enabled"
            },
            "Name": "Fan4",
            "FanName": "Fan4"
        },
        {
            "PhysicalContext": "Backplane",
            "LowerThresholdCritical": null,
            "Reading": 2233,
            "Redundancy": [
                {
                    "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Redundancy/0"
                }
            ],
            "MinReadingRange": null,
            "MaxReadingRange": null,
            "MemberId": "2",
            "ReadingUnits": "RPM",
            "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Fans/2",
            "Status": {
                "Health": "OK",
                "State": "Enabled"
            },
            "Name": "Fan2",
            "FanName": "Fan2"
        },
        {
            "PhysicalContext": "Backplane",
            "LowerThresholdCritical": null,
            "Reading": 2233,
            "Redundancy": [
                {
                    "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Redundancy/0"
                }
            ],
            "MinReadingRange": null,
            "MaxReadingRange": null,
            "MemberId": "1",
            "ReadingUnits": "RPM",
            "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Fans/1",
            "Status": {
                "Health": "OK",
                "State": "Enabled"
            },
            "Name": "Fan1",
            "FanName": "Fan1"
        }
    ],
    "Id": "Thermal",
    "@odata.type": "#Thermal.v1_1_0.Thermal",
    "Name": "Thermal",
    "@odata.context": "/redfish/v1/$metadata#Thermal.Thermal",
    "@odata.id": "/redfish/v1/Chassis/1/Thermal",
    "Temperatures": [
        {
            "MemberId": "CPU1",
            "UpperThresholdCritical": 105,
            "PhysicalContext": "CPU",
            "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Temperatures/CPU1",
            "UpperThresholdNonCritical": 100,
            "SensorNumber": 43,
            "RelatedItem": [
                {
                    "@odata.id": "/redfish/v1/Systems/1"
                }
            ],
            "Name": "CPU1 Temp",
            "LowerThresholdNonCritical": 10,
            "ReadingCelsius": 51,
            "LowerThresholdCritical": null
        },
        {
            "MemberId": "Board",
            "UpperThresholdCritical": 70,
            "PhysicalContext": "SystemBoard",
            "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Temperatures/Board",
            "UpperThresholdNonCritical": 60,
            "SensorNumber": 42,
            "RelatedItem": [
                {
                    "@odata.id": "/redfish/v1/Chassis/1"
                },
                {
                    "@odata.id": "/redfish/v1/Systems/1"
                }
            ],
            "Name": "Board Temp",
            "LowerThresholdNonCritical": 10,
            "ReadingCelsius": 32,
            "LowerThresholdCritical": null
        },
        {
            "UpperThresholdCritical": 39,
            "PhysicalContext": "Intake",
            "RelatedItem": [
                {
                    "@odata.id": "/redfish/v1/Chassis/1"
                },
                {
                    "@odata.id": "/redfish/v1/Systems/1"
                }
            ],
            "LowerThresholdCritical": 5,
            "LowerThresholdNonCritical": 10,
            "MemberId": "Intake",
            "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Temperatures/Intake",
            "SensorNumber": 41,
            "Status": {
                "Health": "OK",
                "State": "Enabled"
            },
            "Name": "Intake Temp",
            "ReadingCelsius": 20,
            "UpperThresholdNonCritical": 37
        },
        {
            "MemberId": "CPU2",
            "UpperThresholdCritical": 105,
            "PhysicalContext": "CPU",
            "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Temperatures/CPU2",
            "UpperThresholdNonCritical": 100,
            "SensorNumber": 44,
            "RelatedItem": [
                {
                    "@odata.id": "/redfish/v1/Systems/1"
                }
            ],
            "Name": "CPU2 Temp",
            "LowerThresholdNonCritical": 10,
            "ReadingCelsius": 52,
            "LowerThresholdCritical": null
        }
    ]
}




________________________________

**Comment by mraineri** [comment]
This may or may not be related, but the ordering of the array looks incorrect. For example, the first fan in the Fans array contains the @odata.id "/redfish/v1/Chassis/1/Thermal#/Fans/3", but that JSON fragment doesn't resolve. The way to read that per RFC 6901 is within the Thermal resource, go to the Fans property, then index 3 in the array. The first entry in the Fans array needs to have the JSON fragment end in 0, the second ends in 1, etc.

**Comment by mraineri** [comment]
Tomas pointed this out to me; the Temperatures are not constructed properly either. For example: "/redfish/v1/Chassis/1/Thermal#/Temperatures/CPU2"

In the above case, "Temperatures" is an array, and it's not possible to index into the array with the value "CPU2".

**Comment by PhillipWatts1012** [comment]
Ok, I will point this out to Paul Vancil when he returns

from conference.

Paul is one of the primary authors of obmc backend.

Original Contributions:

  *   Paul Vancil -- Dell ESI Systems Management Architect
  *   Balaji B Rao -- Dell Software Developer -- integration with OpenBMC
  *   Michael E Brown -- Dell Software Architect -- integration with OpenBMC
  *



________________________________

**Comment by mraineri** [comment]
@PhillipWatts1012 can we close this issue? It seems like the issue is how the URIs are being constructed.

**Comment by PhillipWatts1012** [comment]
I still haven't gotten Paul's comments on this. I don't maintain the RedfishService.  I believe he is out till Monday.

**Comment by PhillipWatts1012** [comment]
Paul agrees the way we are creating the frags is not valid. Closing issue.
