### ISSUE TITLE
How to disable OemCheck in Redfish-Interop-Validator?

### ISSUE THREAD

**Issue by VertivHugo** [DMTF/Redfish-Interop-Validator#49]
I got following error information when run Redfish-Interop-Validator:

>ERROR - The following namespaces are referenced by the service, but are not included in $metadata: 
>OemMessageRegistry.v1_0_0

The OemMessageRegistry.v1_0_0 is an OEM schema.
When i run the Redfish-Interop-Validator service and already add "OemCheck = False" in config.ini. The result is still get above error message in result html file.
Is there any way or possible to avoid OEM schema check?

**Comment by tomasg2012** [comment]
Should be available with 09/14 PR.
