### ISSUE TITLE
Validator fail to check property with "type" : "null" 

### ISSUE THREAD

**Issue by VertivHugo** [DMTF/Redfish-Interop-Validator#51]
Property "UefiTargetBootSourceOverride" definition in schema is:
```
"UefiTargetBootSourceOverride": {
    "description": "This property is the UEFI Device Path of the device to boot from when BootSourceOverrideTarget is UefiTarget.",
    "longDescription": "The value of this property shall be the UEFI device path of the override boot target. The valid values for this property are specified through the Redfish.AllowableValues annotation. BootSourceOverrideEnabled = Continuous is not supported for UEFI Boot Source Override as this setting is defined in UEFI as a one time boot only.",
    "readonly": false,
    "type": [
        "string",
        "null"
    ]
}
```
The real implementation of value "UefiTargetBootSourceOverride" in redfish service is:
```
"Boot": {
        "BootSourceOverrideEnabled": "Disabled",
        "BootSourceOverrideTarget": "None",
        "UefiTargetBootSourceOverride"": null,
        "BootSourceOverrideMode": "Legacy"
}
```
The condition option in porfile to validate property "UefiTargetBootSourceOverride" is:
```
"UefiTargetBootSourceOverride": {
    "ReadRequirement": "Recommended",
    "ConditionalRequirements": [{
        "Purpose": "If UEFI mode is selected, must allow for UEFI target.",
        "CompareProperty": "BootSourceOverrideMode",
        "CompareType": "Equal",
        "CompareValues": ["UEFI"],
        "ReadRequirement": "Mandatory",
        "Comparison": "AnyOf",
        "Values": ["None", "RDOC1", "RDOC2"]
    }]              
}
```
Whatever the value of "Values" i set into conditioin option is ["Test1", "Test2"], ["null", "Test1", "Test2"], [null, "Test1", "Test2"] or ["None", "Test1", "Test2"] to validate property "UefiTargetBootSourceOverride". 
The Validator result is always return fail and the error message is:
>TypeError: argument of type 'NoneType' is not iterable
>ERROR - Could not finish validation check on this payload

##### How to config condition option to process ["type" : "null"] property?

**Comment by tomasg2012** [comment]
I don't think there's sufficient debug information to diagnose this if I ask for a log with `--debug_logging`.  Does this happen if `UefiTarget...` is not null?

I will try to test this with a mockup and see what the problem is.  Is this particular profile you're using public?

**Comment by VertivHugo** [comment]
Attach the log file which add "--debug_logging" option for more debug information. I had reduce some useless messages for upload the file. If any missing, please kindly let me know.
[InteropLog_09_07_2018_152217.txt](https://github.com/DMTF/Redfish-Interop-Validator/files/2360062/InteropLog_09_07_2018_152217.txt)
When the value of property "UefiTargetBootSourceOverride" is not null, the Validation's result is no problem.

**Comment by mraineri** [comment]
@VertivHugo have you been able to run the change @tomasg2012 has pointed out?

**Comment by mraineri** [comment]
The change has actually been put into master, so the fix should be in place now.

**Comment by VertivHugo** [comment]
The issue has been solved at latest version of code. Thanks for help.

**Comment by VertivHugo** [comment]
Close the issue.
