### ISSUE TITLE
Errors found when checking Registry files.

### ISSUE THREAD

**Issue by cactusjiang** [DMTF/Redfish-Interop-Validator#64]
We got some errors by Redfish-Interop-Validator and it seems that Redfish-Interop-Validator doesn't extract the correct context of the resource.

|Resource| error message|
|----------|----------------|
| /redfish/v1/schemas/registries/ResourceEvent.1.0.1.json | ERROR - getResourceObject: Namespace appears nonexistent in SchemaXML: MessageRegistry.v1_0_0.MessageProperty http://redfish.dmtf.org/schemas/v1/MessageRegistryFile_v1.xml
 | /redfish/v1/schemas/registries/Base.1.4.0.json | ERROR - getResourceObject: Namespace appears nonexistent in SchemaXML: MessageRegistry.v1_0_0.MessageProperty http://redfish.dmtf.org/schemas/v1/MessageRegistryFile_v1.xml
|/redfish/v1/schemas/registries/TaskEvent.1.0.1.json| ERROR - getResourceObject: Namespace appears nonexistent in SchemaXML: MessageRegistry.v1_0_0.MessageProperty http://redfish.dmtf.org/schemas/v1/MessageRegistryFile_v1.xml

- Try to modify interop source code, set the context to `None` when the reosurce is message registrey, then, interop would create the corresponding context for it.
  - Adds `context = None`  after [this line](https://github.com/DMTF/Redfish-Interop-Validator/blob/master/traverseService.py#L635)
- After the modification, the issues that mention above are disappear(and the context in the report is correct).

Could someone help to check it? Thanks.

**Comment by tomasg2012** [comment]
While this line of code would fix this problem, I'm having a hard time replicating this error down the pipeline of the program with my own payloads.  I wouldn't hestitate to add this line in a PR, but am still trying to confirm the issue's cause.

**Comment by mraineri** [comment]
Fixed in latest PR
