### ISSUE TITLE
Need a simple text report

### ISSUE THREAD

**Issue by mgarrett33** [DMTF/Redfish-Interop-Validator#66]
The comprehensive log is great, but for purposes of logging bugs against our products, it would be really useful to have a text output report that is easy to read at a glance and has one line per error.  Each error line should contain:

* Schema
* Property (property path) - or Action
* URI associated with the Schema (e.g. if it fails on only some instances of a schema class)
* Error specifics
* Line number in log file to reference for more verbose detail

**Comment by mraineri** [comment]
Assigning to @jautor for now to work with @mgarrett33 for a sample report. Currently we have an HTML report that is heavily based off the Service Validator reporting, so having a concrete example would be useful so we know what to make exactly.

**Comment by mraineri** [comment]
@jautor and @mgarrett33 any updates on the request for a sample?

**Comment by mgarrett33** [comment]
I propose a CSV output that has one line per line in the HTML output detail table.  The goal is that you can load the CSV in a text editor or Excel and do a find-all (or column filter) for "FAIL" and get line results that include the URI/schema info as well as property info.

e.g.
```
URI,Status,Response Time,Context,File Origin,Resource Type,Property Name,Value,Expected,Actual,Result
/redfish/v1/Chassis/1,200,0.268008,http://redfish.dmtf.org/schemas/v1/Chassis_v1.xml,localFile:./SchemaFiles/metadata/Chassis_v1.xml,Chassis.v1_9_1.Chassis,HealthRollup.ReadRequirement,Mandatory,Must Exist,DNE,FAIL
/redfish/v1/Chassis/1,200,0.268008,http://redfish.dmtf.org/schemas/v1/Chassis_v1.xml,localFile:./SchemaFiles/metadata/Chassis_v1.xml,Chassis.v1_9_1.Chassis,Thermal.ReadRequirement,Recommended,Any,Exists,PASS
```

**Comment by tomasg2012** [comment]
The code as it stands outputs CSV to the terminal and log on request of the parameter --csv_report.  Should it be its own file instead?

**Comment by jcleung5549** [comment]
The above question is relevant since a pull request has been created which generates a file - #90

**Comment by jautor** [comment]
Yes, I can speak for @mgarrett33 on this issue - we'd absolutely want a file output for this...

**Comment by tomasg2012** [comment]
Resolved, the tool now contains `htmlLogScraper.py` for scraping HTML files after being generated, while `--csv_report` has a similar function.

**Comment by tomasg2012** [comment]
Oops, actually, we haven't recovered the file into the repo, the last PR incorrectly omitted the file.  Must remedy by next meeting.

**Comment by tomasg2012** [comment]
This should be corrected.
