### ISSUE TITLE
ValidateMinVersion can not get pass for RedfishVersion  in ServiceRoot

### ISSUE THREAD

**Issue by vic-lin-accton** [DMTF/Redfish-Interop-Validator#70]
Hi,

By using the profile 'OCPBaselineHardwareManagement.v1_0_0.json' got from 'https://github.com/opencomputeproject/OCP-Profiles'  it has the "Protocol" section with "MinVersion": "1.0". 

And we have RedfishVersion to be "1.0.2" to be validated.  After run the log shows below Info.
------------------------------
INFO - Testing minVersion 
	('1.0.2', '1.0')
INFO - 	pass False
ERROR - 	No Pass
----------------------------
It seems ValidateMinVersion()  can not get that comparison  passed. However, suppose 1.0.2 is greater than 1.0 and should be pass.

Thanks

// Vic

**Comment by tomasg2012** [comment]
Looking at the function, it's trying a little too specifically to expect a full version string and not just the first two numbers, as in `1.0` should be `1.0.0`, to match `x.y.z`.  Tool seems to have trouble with the missing errata number.

**Comment by mraineri** [comment]
5/2: From inspection with the intent of profiles, we should allow for the absence of the errata version. The tool will need to essentially ignore the errata version of what's reported by the service in this case.

**Comment by mraineri** [comment]
Fixed in latest PR
