### ISSUE TITLE
fail.ServiceRoot.ReadRequirement error

### ISSUE THREAD

**Issue by vic-lin-accton** [DMTF/Redfish-Interop-Validator#71]
By checking the profile 'OCPBaselineHardwareManagement' from https://github.com/opencomputeproject/OCP-Profiles, we got 'fail.ServiceRoot.ReadRequirement' error.

After some digging code, we find the reason might be objRes['ServiceRoot']['mark'] not set to True.
There only all links following the 'ServiceRoot' be checked and marked.  However, in validateURITree() there did not try to mark 'ServiceRoot' after validate top URI itself.

Hope it helps.

**Comment by samerhaj** [comment]
I am seeing the same failure with another profile (not OCP) on at least two different Redfish implementations. Seem in both cases, all instances of "ServiceRoot" in the log indicate success, except in the summary of results:

`ERROR - 1 fail.ServiceRoot.ReadRequirement errors in Service Level Requirements
`
