### ISSUE TITLE
"If Implemented" subordinate resource links treated as Mandatory

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Interop-Validator#77]
The "If Implemented" requirement needs to be handled carefully.  The tool is failing if an "if implemented" subordinate resource link is not present. That could be because the link is a JSON object (may be considering the odata.id as mandatory since the object is present). 

This could be an exception case to be handled.

**Comment by jautor** [comment]
Case like:
```
"Thermal": {
   "ReadRequirement": "IfImplemented"
 }
```

**Comment by samerhaj** [comment]
I am seeing this error with other profiles as well . The Profile fragment I am using is:

        "JobService": {
            "Purpose": "The JobService has the properties for the service itself and has links to the actual list of tasks.",
            "ReadRequirement": "IfImplemented"
        },


The failure I am seeing is:

![image](https://user-images.githubusercontent.com/7462078/59383541-16ad9f00-8d2e-11e9-8bba-b29f9e9f6e95.png)

Feedback from users is that the tool should report such missing resources as a "WARNING" not a "FAIL"...
