### ISSUE TITLE
Conditional requirements not passing

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Interop-Validator#80]
Conditionals with "CompareProperty" don't appear to function properly.  Get an "ERROR - NoPass" in the log and in the HTML output (with no context, either).

Snippet from a Boot object requirement in a ComputerSystem profile:
```
 "UefiTargetBootSourceOverride": {
   "ConditionalRequirements": [
        {
        "CompareProperty": "BootSourceOverrideMode", 
        "Comparison": "Equal", 
        "Purpose": "If UEFI mode is selected, must allow for UEFI target.", 
        "ReadRequirement": "Mandatory", 
        "Values": [
           "UEFI"
          ]
        }
       ], 
      "ReadRequirement": "Recommended", 
      "WriteRequirement": "Mandatory"
    }, 
```
and in payload:

```
        "BootSourceOverrideEnabled": "Once",
        "BootSourceOverrideMode": "UEFI",
        "BootSourceOverrideTarget": "Hdd",
        "UefiTargetBootSourceOverride": "None",
```
the Condition should apply, and the resulting Mandatory requirement is met.  But log output says:

```
INFO - inside complex Boot.UefiTargetBootSourceOverride
INFO - propRequirement with value: None
INFO - Testing ReadRequirement 
	expected:Recommended, exists: True
INFO - 	pass True
INFO - writeable 
	Mandatory
INFO - Evaluating conditionalRequirements
INFO - Testing a comparison 
	('UEFI', 'Equal', [])
INFO - 	pass False
ERROR - 	NoPass
INFO - 	Condition does not apply
```

And in the HTML output - there's a "ERROR - NoPass" for that resource (but no context as to what property or requirement).

**Comment by tomasg2012** [comment]
It should be noted that "Values" is incorrect when using CompareProperty, it's "CompareValues"?

**Comment by jautor** [comment]
ooh, good catch - that would explain the fault...

And a good reminder for folks to check their profile with a JSON schema validator.

**Comment by jautor** [comment]
@tomasg2012 I've looked at the spec and we can add a check/error message here to catch these errors.  If "CompareProperty" exists, then both "CompareType" and "CompareValues" must exist.  If not, the conditional requirement isn't valid and we should throw an error in the log and HTML, and it should say something like "Invalid Profile - ConditionalRequirement for <property> missing Comparison properties".
