### ISSUE TITLE
Cannot verify @ActionInfo in Actions property

### ISSUE THREAD

**Issue by hieutrgvu** [DMTF/Redfish-Interop-Validator#93]
## Description
The current code for checking Action requirement in `commonInterop.py`
https://github.com/DMTF/Redfish-Interop-Validator/blob/a0119ca69f50444d04d7918200c1c3ecc18d03e3/commonInterop.py#L459-L466
only handles for `@Redfish.AllowableValues`. It will treat the below response as fail although the `@Redfish.AllowableValues` can be retrieved in `@Redfish.ActionInfo` URI.
```json
"Actions": {
    "#ComputerSystem.Reset": {
        "@Redfish.ActionInfo": "/redfish/v1/Systems/Self/ResetActionInfo",
        "target": "/redfish/v1/Systems/Self/Actions/ComputerSystem.Reset"
    }
},
```

## Information
+ In Redfish Specification v1.8.0 ([DSP0266](https://www.dmtf.org/sites/default/files/standards/documents/DSP0266_1.8.0.pdf)), Section 9.5.13 mentions:
> To specify the list of supported values for a parameter, the service may include the @Redfish.AllowableValues annotation.
> ...
> The Resource may provide a separate @Redfish.ActionInfo Resource to describe the parameters and values that a particular instance or implementation supports.

+ In Redfish Schema Supplement v2019.3 ([DSP0268](https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2019.3.pdf)), Section "Common objects" specifies that Actions property contains `@Redfish.ActionInfo` and `target`.

+ In Redfish Interoperability Profiles Specification v1.2.0 ([DSP0272](https://www.dmtf.org/sites/default/files/standards/documents/DSP0272_1.2.0.pdf)), Section 8.4.3 only defines that Action requirement contains ReadRequirement, Parameters, and Purpose. The Parameters is the requirement for any parameter available for this Action, but there are no statements specifying it must be located in `@Redfish.AllowableValues` or `@Redfish.ActionInfo` URI.

**Comment by tomasg2012** [comment]
Should be fixed with latest PR.
