### ISSUE TITLE
Cannot validate if property/version is deprecated

### ISSUE THREAD

**Issue by frsauvage** [DMTF/Redfish-Interop-Validator#94]
Hi
I try to validate the Profile Simulator.
From one side:
- Redfish Profile Simulator 
From the other side
- Redfish Interop Validator with:
--> new DSP package DSP8010_2019.3.zip

got the errors:
Something went wrong ... 
KeyError: 'Term' 

for
PostalAddress:GPSCoords, Location:Info, PCIDevices PostalAddress:PostalLocation Fan:FanName

Properties have a deprecated status.
It seems that the Validator do NOT take care of versionDeprecated ?

In getPropertyDetails(), tag['Term'] raises an exception because the 'deprecated' structures are Collection (Redfish.Revisions Collection inside Annotation tag) and propertyTags variable is flatten before. 
like GPSCoords: 
![image](https://user-images.githubusercontent.com/23147820/72274514-a2710c00-362c-11ea-883d-57e161cf3991.png)

Any idea  / suggestion to fix it ? I would be pleased,

Best Regards,
Francine

**Comment by billdodd** [comment]
What profile are you using?

**Comment by frsauvage** [comment]
Hi @billdodd 
My profile :

{
  "SchemaDefinition": "RedfishInteroperabilityProfile.v1_0_0",
  "ProfileName": "Mesca3",
  "ProfileVersion": "1.0.2",
  "OwningEntity": "Atos",
  "Author": "Francine Sauvage",
  "Purpose": "This is a sample Redfish profile.",
  "RequiredProfiles": {
      "DMTFBasic": {
          "MinVersion": "1.0.0"
      }
  },
  "Resources": {
      "ChassisCollection": {
          "PropertyRequirements": {
              "Members": {
                  "MinCount": 1
              }
          }
      }
  }
}

My profile is very simple, just a test to start understanding.

Why did you ask that question ? Is there a link between profile and session ?

Regards,
Francine

**Comment by tomasg2012** [comment]
I believe this might be that the program does not support the type of
Revision/Deprecated format specified in the schema.  Will see if that's a
valid fix.

**Comment by tomasg2012** [comment]
Sadly, I can't seem to replicate the issue, without a log provided.  If possible, a log might help, if one is completed.

Upon a look into the code at line 697, there are two lines that use the statement `tag['Term']`, however they are prefaced by this:

```
            for tag in propertyInnerTags:
                if(not tag.get('Term')):
                    rst.traverseLogger.warn(tag, 'does not contain a Term name')
                elif (tag.get('Term') == 'Redfish.Revisions'):
                    propEntry[tag['Term']] = tag.find_all('Record')
                else:
                    propEntry[tag['Term']] = tag.attrs
```

This should be placing important information about certain tags by their tagname.  I can attempt to rewrite this and put it in a branch named `deprecated-term-fix`

**Comment by mraineri** [comment]
Closing; tool was changed a while ago to not rely on schema, so this issue shouldn't be happening anymore. If there's a similar issue with the latest version, please file a new issue.
