### ISSUE TITLE
failPayloadError in Sessions 

### ISSUE THREAD

**Issue by YousseMes** [DMTF/Redfish-Interop-Validator#95]
Hello 
I get this error evry time when I try to validate the  Profile Simulator with Interop Validator :
DSP package DSP8010_2019.3.zip

**Teminal** : 
_1 failPayloadError errors in /redfish/v1/SessionService/Sessions
Counter({'skipOptional': 139, 'pass': 130, 'metadataNamespaces': 60, 'skipOem': 23, 'passGet': 14, 'serviceNamespaces': 13, 'warningPresent': 
7, 'missingNamespaces': 4, 'badNamespaceInclude': 1, 'reflink': 1, 'failPayloadError': 1})_

Please can you help to fix that ? ,  I'll be grateful :)  

Regards,
**Youssef**.

**Comment by billdodd** [comment]
What profile are you using?

**Comment by tomasg2012** [comment]
It would help to provide a log to demonstrate what the possible issue is specifically.  It should describe what the Error is.  I also don't seem to see any sort of Error in the code like that, unless I'm overlooking...

**Comment by mraineri** [comment]
@YousseMes do you have any of the requested information available? At this point there's not much we can do to debug the issue without more information.

**Comment by tomasg2012** [comment]
If there is a fix to it, it would likely be requiring an updated version of the tool.

Without an example of the payload, we cannot determine what the issue `failPayloadError` means, which is not an error possible in the Interop tool.  Otherwise, the likely issue would be some `@odata` value being incorrectly formatted.

**Comment by mraineri** [comment]
Closing; no updates on the issue for requested information.

If further information is available, please reopen the issue and provided it so we can investigate.
