### ISSUE TITLE
Unable to parse configuration: TypeError("'NoneType' object is not iterable",)

### ISSUE THREAD

**Issue by frsauvage** [DMTF/Redfish-Interop-Validator#99]
Hi,
I just tried the following :
`python3 RedfishInteropValidator.py MyProfile -c config.ini `

I get:
Unable to parse configuration: TypeError("'NoneType' object is not iterable",)

Config:

> 
> [Information]
> Updated = May 8, 2017
> Description = Redfish Interop Conformance Tool 0.91
> 
> [SystemInformation]
> TargetIP = 10.10.10.10
> SystemInfo = Test Config, place your own description of target system here
> UserName = root
> Password = my_pass
> AuthType = None
> Token = 123456SESSIONNauthcode
> UseSSL = False
> CertificateCheck = Off
> CertificateBundle = 
> 
> [Options]
> MetadataFilePath = ./SchemaFiles
> CacheMode = Off
> CacheFilePath =
> SchemaSuffix = _v1.xml
> Timeout = 30
> HttpProxy =
> HttpsProxy =
> LocalOnlyMode = True
> ServiceMode = Off
> 
> [Validator]
> PayloadMode = Default
> PayloadFilePath = 
> LogPath = ./logs 
> WarnRecommended = False

What is wrong ?

Best Regards,
Francine

**Comment by tomasg2012** [comment]
If possible, could you run this same command but appended with a `-v` parameter?  The config seems to run fine so I cannot seem to diagnose the problem.

**Comment by frsauvage** [comment]
Hi @tomasg2012 
Thank to answer me.
Sorry for the delay : french time :-)
I get that 
> 
[root@localhost Redfish-Interop-Validator]# python3 RedfishInteropValidator.py MyProfile -c config.ini -v
Unsupported updated
Unsupported description
Unsupported payloadmode
Unsupported logpath
Unsupported warnrecommended
Exception caught while parsing configuration
Traceback (most recent call last):
  File "RedfishInteropValidator.py", line 429, in main
    config, default_list = rst.setByArgparse(args)
TypeError: 'NoneType' object is not iterable
Unable to parse configuration: TypeError("'NoneType' object is not iterable",)

Best Regards
Francine

**Comment by frsauvage** [comment]
Sorry, previous version 1.1.4, I did a "git pull",  => I close it
